// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "23-flare"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const play_23FlareSemantic = {
  "name": "23 Flare (Set Play vs 2-3 Zone)",
  "tag": "zone-offense",
  "desc": "A quick-hitter against a 2-3 zone. The ball moves wing-to-corner-and-back to drag the zone's wing defender, then a sudden flare screen by the high-post frees the best shooter for an open three on the wing. Best used sparingly for maximum surprise.",
  "players": {
    "1": "top_of_key",
    "2": "left_wing",
    "3": "right_wing",
    "4": "left_corner",
    "5": "left_elbow"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Ball to Wing",
      "text": "1 passes to 2 on the left wing while staying near the top of the key.",
      "detail": "1 holds position at the top — the pass initiates the action. 5 is already at the strong-side elbow.",
      "actions": [
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "2"
        }
      ]
    },
    {
      "label": "Phase 2 — Ball to Corner and Back",
      "text": "2 passes to 4 in the corner. 4 passes back to 2, then begins walking defender toward the rim.",
      "detail": "The quick reversal corner pass and return occupies x4 and begins setting up 4's blocking action later.",
      "actions": [
        {
          "type": "pass",
          "from_player": "2",
          "to_player": "4"
        },
        {
          "type": "pass",
          "from_player": "4",
          "to_player": "2"
        },
        {
          "type": "cut",
          "player": "4",
          "to": "left_block",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 3 — Drag the Zone Wing Defender",
      "text": "2 takes 2–3 dribbles toward the top of the key, forcing X2 to follow.",
      "detail": "This dribble toward the top is deliberate — it pulls X2 out of position and sets up the flare screen.",
      "actions": [
        {
          "type": "dribble",
          "player": "2",
          "to": "left_slot",
          "bias": "away_from_basket"
        }
      ]
    },
    {
      "label": "Phase 4 — Flare Screen Triggered",
      "text": "2 passes to 1 at the top. 5 immediately sets a flare screen for 2. 4 screens to prevent x4 from contesting.",
      "detail": "The flare screen must be sudden to catch X2 off guard. 4's screen near the block prevents their defender from closing out on the shooter.",
      "actions": [
        {
          "type": "pass",
          "from_player": "2",
          "to_player": "1"
        },
        {
          "type": "screen",
          "screener": "5",
          "cutter": "2",
          "at": "high_post",
          "cutter_to": "left_wing"
        }
      ]
    },
    {
      "label": "Phase 5 — Shooter Uses Flare Screen for Open Three",
      "text": "2 uses the flare screen and relocates to the wing. 1 delivers the pass to 2 for the open three-pointer.",
      "detail": "1 passes over the top to the now-open 2 on the wing. 4's block on x4 prevents a closeout.",
      "actions": [
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "2"
        }
      ]
    }
  ]
} as const;

export const play_23Flare: Play = {
  "name": "23 Flare (Set Play vs 2-3 Zone)",
  "tag": "zone-offense",
  "desc": "A quick-hitter against a 2-3 zone. The ball moves wing-to-corner-and-back to drag the zone's wing defender, then a sudden flare screen by the high-post frees the best shooter for an open three on the wing. Best used sparingly for maximum surprise.",
  "players": {
    "1": [
      0,
      32
    ],
    "2": [
      -15,
      22
    ],
    "3": [
      15,
      22
    ],
    "4": [
      -24,
      4
    ],
    "5": [
      -8,
      19
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Ball to Wing",
      "text": "1 passes to 2 on the left wing while staying near the top of the key.",
      "detail": "1 holds position at the top — the pass initiates the action. 5 is already at the strong-side elbow.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 L -15 22",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "2"
          }
        }
      ]
    },
    {
      "label": "Phase 2 — Ball to Corner and Back",
      "text": "2 passes to 4 in the corner. 4 passes back to 2, then begins walking defender toward the rim.",
      "detail": "The quick reversal corner pass and return occupies x4 and begins setting up 4's blocking action later.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M -15 22 L -24 4",
          "dashed": true,
          "ball": {
            "from": "2",
            "to": "4"
          }
        },
        {
          "marker": "arrow",
          "path": "M -24 4 L -15 22",
          "dashed": true,
          "ball": {
            "from": "4",
            "to": "2"
          }
        },
        {
          "marker": "arrow",
          "path": "M -24 4 C -15.67 4.47, -10.34 4.81, -8 5",
          "move": {
            "id": "4",
            "to": [
              -8,
              5
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3 — Drag the Zone Wing Defender",
      "text": "2 takes 2–3 dribbles toward the top of the key, forcing X2 to follow.",
      "detail": "This dribble toward the top is deliberate — it pulls X2 out of position and sets up the flare screen.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M -15 22 C -15.25 25.29, -14.58 27.29, -13 28",
          "move": {
            "id": "2",
            "to": [
              -13,
              28
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 4 — Flare Screen Triggered",
      "text": "2 passes to 1 at the top. 5 immediately sets a flare screen for 2. 4 screens to prevent x4 from contesting.",
      "detail": "The flare screen must be sudden to catch X2 off guard. 4's screen near the block prevents their defender from closing out on the shooter.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M -13 28 L 0 32",
          "dashed": true,
          "ball": {
            "from": "2",
            "to": "1"
          }
        },
        {
          "marker": "screen",
          "path": "M -8 19 C -4.61 15.55, -1.95 14.22, 0 15",
          "move": {
            "id": "5",
            "to": [
              0,
              15
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -13 28 C -12.59 25.64, -13.25 23.64, -15 22",
          "move": {
            "id": "2",
            "to": [
              -15,
              22
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 5 — Shooter Uses Flare Screen for Open Three",
      "text": "2 uses the flare screen and relocates to the wing. 1 delivers the pass to 2 for the open three-pointer.",
      "detail": "1 passes over the top to the now-open 2 on the wing. 4's block on x4 prevents a closeout.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 L -15 22",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "2"
          }
        }
      ]
    }
  ]
};
