// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "32-lob"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const play_32LobSemantic = {
  "name": "32 Lob",
  "tag": "zone-offense",
  "desc": "A quick-hitter set play vs 2-3 zone designed to score a backdoor lob for an athletic perimeter player. The offense overloads one side to shift the zone, reverses the ball, and uses a weak-side screen on the baseline to free a cutter for an alley-oop at the rim.",
  "players": {
    "1": "top_of_key",
    "2": "right_wing",
    "3": "left_wing",
    "4": "high_post",
    "5": "left_elbow"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Wing 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 – Ball Entry",
      "text": "Guard 1 passes to Wing 2 on the right wing to initiate the play and begin forcing the zone to shift.",
      "detail": "The entry pass gets the ball to the strong-side wing. The zone's low defender (x4) is responsible for tracking ball-side action.",
      "actions": [
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "2"
        }
      ]
    },
    {
      "label": "Phase 2 – Corner Dribble & Weak-Side Slide",
      "text": "Wing 2 dribbles toward the right corner, forcing x4 to follow. Simultaneously, Wing 3 quietly slides from the left wing down to the left corner behind the defense's sight lines.",
      "detail": "2's drive to the corner commits the zone's strong-side low defender. 3 must slide late and undetected to avoid tipping off the lob action.",
      "actions": [
        {
          "type": "dribble",
          "player": "2",
          "to": "right_corner",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "3",
          "to": "left_corner",
          "bias": "away_from_basket"
        }
      ]
    },
    {
      "label": "Phase 3 – Ball Reversal",
      "text": "Wing 2 passes back to Guard 1 at the top. The zone is now committed to the strong side.",
      "detail": "The reversal is the trigger for the weak-side screen and lob. 1 must be ready to throw the lob immediately after receiving.",
      "actions": [
        {
          "type": "pass",
          "from_player": "2",
          "to_player": "1"
        }
      ]
    },
    {
      "label": "Phase 4 – Weak-Side Screen on Baseline Defender",
      "text": "Post 5 slides to the left block and sets a screen on the weak-side low zone defender, nudging them up the lane and creating a clear baseline lane to the rim.",
      "detail": "5's screen is the key block — it must pin the low zone defender just long enough for 3 to get a step on the defense.",
      "actions": [
        {
          "type": "screen",
          "screener": "5",
          "cutter": "3",
          "at": "left_block",
          "cutter_to": "low_post",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 5 – Backdoor Lob",
      "text": "Wing 3 cuts hard off 5's screen toward the rim. Guard 1 delivers a lob pass for Wing 3 to finish with a dunk or layup at the basket.",
      "detail": "Timing is critical — 1 must release the lob as 3 turns the corner off the screen. The lob should be placed above the backboard so only 3 can catch it in stride.",
      "actions": [
        {
          "type": "cut",
          "player": "3",
          "to": "low_post",
          "bias": "toward_basket"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "3"
        }
      ]
    }
  ]
} as const;

export const play_32Lob: Play = {
  "name": "32 Lob",
  "tag": "zone-offense",
  "desc": "A quick-hitter set play vs 2-3 zone designed to score a backdoor lob for an athletic perimeter player. The offense overloads one side to shift the zone, reverses the ball, and uses a weak-side screen on the baseline to free a cutter for an alley-oop at the rim.",
  "players": {
    "1": [
      0,
      32
    ],
    "2": [
      15,
      22
    ],
    "3": [
      -15,
      22
    ],
    "4": [
      0,
      15
    ],
    "5": [
      -8,
      19
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Wing 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 – Ball Entry",
      "text": "Guard 1 passes to Wing 2 on the right wing to initiate the play and begin forcing the zone to shift.",
      "detail": "The entry pass gets the ball to the strong-side wing. The zone's low defender (x4) is responsible for tracking ball-side action.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 L 15 22",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "2"
          }
        }
      ]
    },
    {
      "label": "Phase 2 – Corner Dribble & Weak-Side Slide",
      "text": "Wing 2 dribbles toward the right corner, forcing x4 to follow. Simultaneously, Wing 3 quietly slides from the left wing down to the left corner behind the defense's sight lines.",
      "detail": "2's drive to the corner commits the zone's strong-side low defender. 3 must slide late and undetected to avoid tipping off the lob action.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 15 22 C 15.21 14.89, 18.21 8.89, 24 4",
          "move": {
            "id": "2",
            "to": [
              24,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -15 22 C -20.79 17.11, -23.79 11.11, -24 4",
          "move": {
            "id": "3",
            "to": [
              -24,
              4
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3 – Ball Reversal",
      "text": "Wing 2 passes back to Guard 1 at the top. The zone is now committed to the strong side.",
      "detail": "The reversal is the trigger for the weak-side screen and lob. 1 must be ready to throw the lob immediately after receiving.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 24 4 L 0 32",
          "dashed": true,
          "ball": {
            "from": "2",
            "to": "1"
          }
        }
      ]
    },
    {
      "label": "Phase 4 – Weak-Side Screen on Baseline Defender",
      "text": "Post 5 slides to the left block and sets a screen on the weak-side low zone defender, nudging them up the lane and creating a clear baseline lane to the rim.",
      "detail": "5's screen is the key block — it must pin the low zone defender just long enough for 3 to get a step on the defense.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 19 C -5.71 12.4, -5.71 7.73, -8 5",
          "move": {
            "id": "5",
            "to": [
              -8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -24 4 C -13 4.73, -5 5.4, 0 6",
          "move": {
            "id": "3",
            "to": [
              0,
              6
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 5 – Backdoor Lob",
      "text": "Wing 3 cuts hard off 5's screen toward the rim. Guard 1 delivers a lob pass for Wing 3 to finish with a dunk or layup at the basket.",
      "detail": "Timing is critical — 1 must release the lob as 3 turns the corner off the screen. The lob should be placed above the backboard so only 3 can catch it in stride.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 6 C 0 6, 0 6, 0 6",
          "move": {
            "id": "3",
            "to": [
              0,
              6
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 32 L 0 6",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "3"
          }
        }
      ]
    }
  ]
};
