// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "blob-yo-yo-updated"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const blobYoYoUpdatedSemantic = {
  "name": "BLOB Yo-Yo",
  "tag": "BLOB",
  "desc": "A simple, effective BLOB play from a box formation. Both guards simultaneously set up-screens for the two post players, who explode to the basket for layups. The inbounder (PG) reads the defense and passes to the open cutter. If neither cutter is open, the weak-side guard wings out as a safety valve.",
  "players": {
    "1": "baseline_center",
    "2": "right_block",
    "3": "left_block",
    "4": "right_elbow",
    "5": "left_elbow"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Simultaneous Up-Screens",
      "text": "2 steps up and sets an up-screen for 4 at the right elbow; 3 steps up and sets an up-screen for 5 at the left elbow. Screeners face each other at the start to disguise the play, then actively seek out the defenders.",
      "actions": [
        {
          "type": "screen",
          "screener": "2",
          "cutter": "4",
          "at": "right_elbow",
          "cutter_to": "right_short_corner",
          "bias": "toward_basket"
        },
        {
          "type": "screen",
          "screener": "3",
          "cutter": "5",
          "at": "left_elbow",
          "cutter_to": "left_short_corner",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 2 — Post Players Explode to the Basket",
      "text": "4 and 5 cut hard off the outside of their respective screens and explode to the basket on their own sides of the lane. Both show target hands as they attack the rim.",
      "actions": [
        {
          "type": "cut",
          "player": "4",
          "to": "right_block",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "5",
          "to": "left_block",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 3 — PG Decision and Pass",
      "text": "1 reads the defense and delivers the inbound pass to whichever cutter (4 or 5) is open at the rim for a layup. The diagram shows the pass going to 5 (weak-side), but either target is live.",
      "actions": [
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "5"
        }
      ]
    },
    {
      "label": "Phase 4 — Safety Valve",
      "text": "If neither 4 nor 5 is open, 3 cuts from the left elbow area out to the left wing to receive the inbound pass for a mid-range shot or to bring the ball up and reset the offense.",
      "actions": [
        {
          "type": "cut",
          "player": "3",
          "to": "left_wing",
          "bias": "away_from_basket"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "3"
        }
      ]
    }
  ]
} as const;

export const blobYoYoUpdated: Play = {
  "name": "BLOB Yo-Yo",
  "tag": "BLOB",
  "desc": "A simple, effective BLOB play from a box formation. Both guards simultaneously set up-screens for the two post players, who explode to the basket for layups. The inbounder (PG) reads the defense and passes to the open cutter. If neither cutter is open, the weak-side guard wings out as a safety valve.",
  "players": {
    "1": [
      0,
      1
    ],
    "2": [
      8,
      5
    ],
    "3": [
      -8,
      5
    ],
    "4": [
      8,
      19
    ],
    "5": [
      -8,
      19
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Simultaneous Up-Screens",
      "text": "2 steps up and sets an up-screen for 4 at the right elbow; 3 steps up and sets an up-screen for 5 at the left elbow. Screeners face each other at the start to disguise the play, then actively seek out the defenders.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 8 5 C 5.71 7.73, 5.71 12.4, 8 19",
          "move": {
            "id": "2",
            "to": [
              8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 19 C 8.01 12.61, 10.67 7.61, 16 4",
          "move": {
            "id": "4",
            "to": [
              16,
              4
            ]
          }
        },
        {
          "marker": "screen",
          "path": "M -8 5 C -5.71 7.73, -5.71 12.4, -8 19",
          "move": {
            "id": "3",
            "to": [
              -8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 19 C -8.01 12.61, -10.67 7.61, -16 4",
          "move": {
            "id": "5",
            "to": [
              -16,
              4
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2 — Post Players Explode to the Basket",
      "text": "4 and 5 cut hard off the outside of their respective screens and explode to the basket on their own sides of the lane. Both show target hands as they attack the rim.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 16 4 C 11.32 4.46, 8.66 4.79, 8 5",
          "move": {
            "id": "4",
            "to": [
              8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -16 4 C -11.32 4.46, -8.66 4.79, -8 5",
          "move": {
            "id": "5",
            "to": [
              -8,
              5
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3 — PG Decision and Pass",
      "text": "1 reads the defense and delivers the inbound pass to whichever cutter (4 or 5) is open at the rim for a layup. The diagram shows the pass going to 5 (weak-side), but either target is live.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 1 L -8 5",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "5"
          }
        }
      ]
    },
    {
      "label": "Phase 4 — Safety Valve",
      "text": "If neither 4 nor 5 is open, 3 cuts from the left elbow area out to the left wing to receive the inbound pass for a mid-range shot or to bring the ball up and reset the offense.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M -8 19 C -11.48 21.52, -13.81 22.52, -15 22",
          "move": {
            "id": "3",
            "to": [
              -15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 1 L -15 22",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "3"
          }
        }
      ]
    }
  ]
};
