// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "blob-flip"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const blobFlipSemantic = {
  "name": "Flip (BLOB vs Man-to-Man)",
  "tag": "BLOB",
  "desc": "A simple BLOB play from a box formation. Guards flash to corners to clear the paint, a cross screen by the ball-side post frees the opposite post to cut to the rim, and then the screener seals and flashes to the other side. Both post players attack the rim simultaneously, forcing the inbounder (1) to read and deliver to the open layup.",
  "players": {
    "1": "baseline_center",
    "2": "right_block",
    "3": "left_block",
    "4": "right_elbow",
    "5": "left_elbow"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Guards Flash to Corners",
      "text": "1 slaps the ball to start the play. 2 and 3 immediately flash hard to opposite corners, calling for the ball to drag their defenders away from the paint.",
      "detail": "The corners must be cleared to open passing lanes into the post.",
      "actions": [
        {
          "type": "cut",
          "player": "3",
          "to": "left_corner",
          "bias": "away_from_basket"
        },
        {
          "type": "cut",
          "player": "2",
          "to": "right_corner",
          "bias": "away_from_basket"
        }
      ]
    },
    {
      "label": "Phase 2 — Cross Screen",
      "text": "5 sets a cross screen on 4's defender. 4 immediately uses the screen and flashes to the ball-side (left) low block, calling for the basketball. The screen must be set on the back hip of the defender.",
      "detail": "Screen angle is critical — set on the back hip so the defender cannot slip underneath and beat 4 to the rim.",
      "actions": [
        {
          "type": "screen",
          "screener": "5",
          "cutter": "4",
          "at": "high_post",
          "cutter_to": "left_block"
        }
      ]
    },
    {
      "label": "Phase 3 — Screener Seals and Flashes",
      "text": "After setting the screen, 5 seals 4's defender and pivots, then flashes to the right block (opposite side of the rim). Both 4 and 5 now threaten the basket from opposite sides, showing target hands.",
      "detail": "Post players must show target hands to indicate where they want the pass as they flash to the rim.",
      "actions": [
        {
          "type": "cut",
          "player": "5",
          "to": "right_block",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 4 — Passer Reads and Delivers",
      "text": "1 reads the defense and passes in-bounds to whichever post player (4 at left block or 5 at right block) is open for the layup. Safety valve: if neither post is available, 3 cuts to the top of the key to receive a lob pass over the top.",
      "detail": "1 must be the best passer — this play demands a quick, accurate read and delivery.",
      "actions": [
        {
          "type": "cut",
          "player": "3",
          "to": "top_of_key",
          "bias": "away_from_basket"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "4"
        }
      ]
    }
  ]
} as const;

export const blobFlip: Play = {
  "name": "Flip (BLOB vs Man-to-Man)",
  "tag": "BLOB",
  "desc": "A simple BLOB play from a box formation. Guards flash to corners to clear the paint, a cross screen by the ball-side post frees the opposite post to cut to the rim, and then the screener seals and flashes to the other side. Both post players attack the rim simultaneously, forcing the inbounder (1) to read and deliver to the open layup.",
  "players": {
    "1": [
      0,
      1
    ],
    "2": [
      8,
      5
    ],
    "3": [
      -8,
      5
    ],
    "4": [
      8,
      19
    ],
    "5": [
      -8,
      19
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Guards Flash to Corners",
      "text": "1 slaps the ball to start the play. 2 and 3 immediately flash hard to opposite corners, calling for the ball to drag their defenders away from the paint.",
      "detail": "The corners must be cleared to open passing lanes into the post.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M -8 5 C -16.33 4.53, -21.66 4.19, -24 4",
          "move": {
            "id": "3",
            "to": [
              -24,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 5 C 16.33 4.53, 21.66 4.19, 24 4",
          "move": {
            "id": "2",
            "to": [
              24,
              4
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2 — Cross Screen",
      "text": "5 sets a cross screen on 4's defender. 4 immediately uses the screen and flashes to the ball-side (left) low block, calling for the basketball. The screen must be set on the back hip of the defender.",
      "detail": "Screen angle is critical — set on the back hip so the defender cannot slip underneath and beat 4 to the rim.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 19 C -4.61 15.55, -1.95 14.22, 0 15",
          "move": {
            "id": "5",
            "to": [
              0,
              15
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 19 C 5.19 11.45, -0.15 6.79, -8 5",
          "move": {
            "id": "4",
            "to": [
              -8,
              5
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3 — Screener Seals and Flashes",
      "text": "After setting the screen, 5 seals 4's defender and pivots, then flashes to the right block (opposite side of the rim). Both 4 and 5 now threaten the basket from opposite sides, showing target hands.",
      "detail": "Post players must show target hands to indicate where they want the pass as they flash to the rim.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 15 C 0.73 9.37, 3.4 6.04, 8 5",
          "move": {
            "id": "5",
            "to": [
              8,
              5
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 4 — Passer Reads and Delivers",
      "text": "1 reads the defense and passes in-bounds to whichever post player (4 at left block or 5 at right block) is open for the layup. Safety valve: if neither post is available, 3 cuts to the top of the key to receive a lob pass over the top.",
      "detail": "1 must be the best passer — this play demands a quick, accurate read and delivery.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M -24 4 C -18.06 15.52, -10.06 24.85, 0 32",
          "move": {
            "id": "3",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 1 L -8 5",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "4"
          }
        }
      ]
    }
  ]
};
