// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "blob-box-gate-updated"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const blobBoxGateUpdatedSemantic = {
  "name": "BLOB Box Gate",
  "tag": "BLOB",
  "desc": "From a box formation, 2 sets a back screen for 5 cutting to the rim, then sprints off a gate screen from 3 and 4 for a wing catch-and-shoot. As a third option, 1 steps in and sets a cross screen for 5 to post up on the ball-side block.",
  "players": {
    "1": "baseline_center",
    "2": "left_block",
    "3": "right_block",
    "4": "right_elbow",
    "5": "left_elbow"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 – Back Screen for Center Layup",
      "text": "2 sets a back screen for 5 at the left elbow. 5 cuts hard to the rim off the screen, reading a possible inbound pass for a layup. 3 begins to move up the key, timing the start of the gate screen.",
      "detail": "2 screens for 5 at the left elbow; 5 dives to the low post / rim area. Critically, 3 must NOT move too early or the defense will read the gate.",
      "actions": [
        {
          "type": "screen",
          "screener": "2",
          "cutter": "5",
          "at": "left_elbow",
          "cutter_to": "low_post"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "5"
        }
      ]
    },
    {
      "label": "Phase 2 – Gate Screen for Shooter",
      "text": "Immediately after setting the back screen, 2 sprints off a gate screen set simultaneously by 3 and 4. 2 catches on the right wing for a catch-and-shoot. 1 passes to 2's inside shoulder. 3 and 4 clear to the top of the key after screening.",
      "detail": "3 and 4 form the gate; 2 uses the gap between them to curl to the right wing. Pass must hit the inside shoulder for a clean catch-and-shoot. 3 and 4 clear high after screening.",
      "actions": [
        {
          "type": "screen",
          "screener": "3",
          "cutter": "2",
          "at": "right_slot",
          "cutter_to": "right_wing"
        },
        {
          "type": "cut",
          "player": "4",
          "to": "top_of_key",
          "bias": "away_from_basket"
        }
      ]
    },
    {
      "label": "Phase 3 – Cross Screen for Post (Tertiary)",
      "text": "1 steps in from the baseline and sets a cross screen for 5. 5 uses the screen to duck in or post up on the ball-side low block. This gives the inbounder — a smaller defender's matchup — a size-mismatch advantage on the helper.",
      "detail": "1 steps inbound and screens across for 5. 5 seals on the right block for a post feed. 2 holds the right wing as the primary passer.",
      "actions": [
        {
          "type": "screen",
          "screener": "1",
          "cutter": "5",
          "at": "high_post",
          "cutter_to": "right_block"
        },
        {
          "type": "pass",
          "from_player": "2",
          "to_player": "5"
        }
      ]
    }
  ]
} as const;

export const blobBoxGateUpdated: Play = {
  "name": "BLOB Box Gate",
  "tag": "BLOB",
  "desc": "From a box formation, 2 sets a back screen for 5 cutting to the rim, then sprints off a gate screen from 3 and 4 for a wing catch-and-shoot. As a third option, 1 steps in and sets a cross screen for 5 to post up on the ball-side block.",
  "players": {
    "1": [
      0,
      1
    ],
    "2": [
      -8,
      5
    ],
    "3": [
      8,
      5
    ],
    "4": [
      8,
      19
    ],
    "5": [
      -8,
      19
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 – Back Screen for Center Layup",
      "text": "2 sets a back screen for 5 at the left elbow. 5 cuts hard to the rim off the screen, reading a possible inbound pass for a layup. 3 begins to move up the key, timing the start of the gate screen.",
      "detail": "2 screens for 5 at the left elbow; 5 dives to the low post / rim area. Critically, 3 must NOT move too early or the defense will read the gate.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 5 C -5.71 7.73, -5.71 12.4, -8 19",
          "move": {
            "id": "2",
            "to": [
              -8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 19 C -3.88 12.04, -1.22 7.71, 0 6",
          "move": {
            "id": "5",
            "to": [
              0,
              6
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 1 L 0 6",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "5"
          }
        }
      ]
    },
    {
      "label": "Phase 2 – Gate Screen for Shooter",
      "text": "Immediately after setting the back screen, 2 sprints off a gate screen set simultaneously by 3 and 4. 2 catches on the right wing for a catch-and-shoot. 1 passes to 2's inside shoulder. 3 and 4 clear to the top of the key after screening.",
      "detail": "3 and 4 form the gate; 2 uses the gap between them to curl to the right wing. Pass must hit the inside shoulder for a clean catch-and-shoot. 3 and 4 clear high after screening.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 8 5 C 7.62 10.47, 9.29 18.14, 13 28",
          "move": {
            "id": "3",
            "to": [
              13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 19 C -0.85 23.97, 6.82 24.97, 15 22",
          "move": {
            "id": "2",
            "to": [
              15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 19 C 5.91 26.28, 3.25 30.61, 0 32",
          "move": {
            "id": "4",
            "to": [
              0,
              32
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3 – Cross Screen for Post (Tertiary)",
      "text": "1 steps in from the baseline and sets a cross screen for 5. 5 uses the screen to duck in or post up on the ball-side low block. This gives the inbounder — a smaller defender's matchup — a size-mismatch advantage on the helper.",
      "detail": "1 steps inbound and screens across for 5. 5 seals on the right block for a post feed. 2 holds the right wing as the primary passer.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 0 1 C 0 2.67, 0 7.33, 0 15",
          "move": {
            "id": "1",
            "to": [
              0,
              15
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 6 L 8 5",
          "move": {
            "id": "5",
            "to": [
              8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 15 22 L 8 5",
          "dashed": true,
          "ball": {
            "from": "2",
            "to": "5"
          }
        }
      ]
    }
  ]
};
