// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "blob-stack-man"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const blobStackManSemantic = {
  "name": "Stack (BLOB vs Man-to-Man — Simple Version)",
  "tag": "BLOB",
  "desc": "A simple youth BLOB play from a stacked formation. The first two players in the stack cut hard to clear defenders, leaving the third player open to step in and receive the inbound pass near the block for a short shot.",
  "players": {
    "1": "right_elbow",
    "2": "baseline_right",
    "3": "right_block",
    "4": "right_slot",
    "5": "low_post"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "2",
  "phases": [
    {
      "label": "Phase 1",
      "text": "1 blasts hard to the right corner calling for the ball. Simultaneously, 4 cuts hard across the paint to the opposite (left) block, also calling for the ball. Both cuts must be convincing to pull defenders out of the paint.",
      "actions": [
        {
          "type": "cut",
          "player": "1",
          "to": "right_corner",
          "bias": "away_from_basket"
        },
        {
          "type": "cut",
          "player": "4",
          "to": "left_block",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 2",
      "text": "With 1 and 4 having cleared their defenders, 3 steps in near the block and receives the inbound pass from 2 for a short shot close to the rim. 3 is the primary scoring option.",
      "actions": [
        {
          "type": "cut",
          "player": "3",
          "to": "right_short_corner",
          "bias": "toward_basket"
        },
        {
          "type": "pass",
          "from_player": "2",
          "to_player": "3"
        }
      ]
    },
    {
      "label": "Phase 3",
      "text": "If 3 is covered and the primary options are denied, 5 steps out to the top of the key as a safety valve to receive the inbound pass and reset the offense.",
      "actions": [
        {
          "type": "cut",
          "player": "5",
          "to": "top_of_key",
          "bias": "away_from_basket"
        },
        {
          "type": "pass",
          "from_player": "2",
          "to_player": "5"
        }
      ]
    }
  ]
} as const;

export const blobStackMan: Play = {
  "name": "Stack (BLOB vs Man-to-Man — Simple Version)",
  "tag": "BLOB",
  "desc": "A simple youth BLOB play from a stacked formation. The first two players in the stack cut hard to clear defenders, leaving the third player open to step in and receive the inbound pass near the block for a short shot.",
  "players": {
    "1": [
      8,
      19
    ],
    "2": [
      10,
      1
    ],
    "3": [
      8,
      5
    ],
    "4": [
      13,
      28
    ],
    "5": [
      0,
      6
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "2",
  "phases": [
    {
      "label": "Phase 1",
      "text": "1 blasts hard to the right corner calling for the ball. Simultaneously, 4 cuts hard across the paint to the opposite (left) block, also calling for the ball. Both cuts must be convincing to pull defenders out of the paint.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 8 19 C 16.13 15.09, 21.46 10.09, 24 4",
          "move": {
            "id": "1",
            "to": [
              24,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 13 28 C 5.35 17.4, -1.65 9.74, -8 5",
          "move": {
            "id": "4",
            "to": [
              -8,
              5
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2",
      "text": "With 1 and 4 having cleared their defenders, 3 steps in near the block and receives the inbound pass from 2 for a short shot close to the rim. 3 is the primary scoring option.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 8 5 C 8.66 4.79, 11.32 4.46, 16 4",
          "move": {
            "id": "3",
            "to": [
              16,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 10 1 L 16 4",
          "dashed": true,
          "ball": {
            "from": "2",
            "to": "3"
          }
        }
      ]
    },
    {
      "label": "Phase 3",
      "text": "If 3 is covered and the primary options are denied, 5 steps out to the top of the key as a safety valve to receive the inbound pass and reset the offense.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 6 C 0 17.67, 0 26.33, 0 32",
          "move": {
            "id": "5",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 10 1 L 0 32",
          "dashed": true,
          "ball": {
            "from": "2",
            "to": "5"
          }
        }
      ]
    }
  ]
};
