// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "blob-belmont-flash"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const blobBelmontFlashSemantic = {
  "name": "BLOB: Belmont Flash (vs 2-3 Zone)",
  "tag": "BLOB",
  "desc": "A baseline out-of-bounds play vs the 2-3 zone. The in-bounder (best shooter) triggers a weak-side flash to pull the middle defender, then curls off a screen to the ball-side corner for an open three. Counter option is a post feed on the low block.",
  "players": {
    "1": "left_block",
    "2": "baseline_center",
    "3": "right_block",
    "4": "right_elbow",
    "5": "left_elbow"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "2",
  "phases": [
    {
      "label": "Phase 1 – Initial Entry",
      "text": "3 pops out to the right wing to receive the inbound pass from 2. Simultaneously, 1 cuts from the weak-side block up to the top of the key as a safety-valve relay option.",
      "detail": "2 looks to hit 3 immediately on the pop. 1's cut to the top gives a second outlet if 3 is denied.",
      "actions": [
        {
          "type": "cut",
          "player": "3",
          "to": "right_wing"
        },
        {
          "type": "cut",
          "player": "1",
          "to": "top_of_key"
        },
        {
          "type": "pass",
          "from_player": "2",
          "to_player": "3"
        }
      ]
    },
    {
      "label": "Phase 2 – Weak-Side Flash",
      "text": "On 3's catch, 4 immediately flashes from the right elbow to the high post / middle of the key. 3 passes to 4, drawing the middle zone defender (x5) toward the lane.",
      "detail": "The flash must be sharp and timed to 3's catch. x5 collapsing on 4 is the key that opens the corner.",
      "actions": [
        {
          "type": "cut",
          "player": "4",
          "to": "high_post",
          "bias": "toward_basket"
        },
        {
          "type": "pass",
          "from_player": "3",
          "to_player": "4"
        }
      ]
    },
    {
      "label": "Phase 3 – Screen & Corner Cut",
      "text": "5 steps across and sets a screen on the ball-side low post defender (x3) at the right block. 2 steps inbounds and curls around 5's screen to the right corner for the catch-and-shoot three. 4 reads the defense and delivers the pass to 2.",
      "detail": "This is the primary scoring action. 4 must read x3: if caught by 5's screen, fire to 2 in the corner.",
      "actions": [
        {
          "type": "screen",
          "screener": "5",
          "cutter": "2",
          "at": "right_block",
          "cutter_to": "right_corner"
        },
        {
          "type": "pass",
          "from_player": "4",
          "to_player": "2"
        }
      ]
    },
    {
      "label": "Phase 4 – Counter: Post Feed",
      "text": "If x3 fights over 5's screen to contest 2, x5 is already occupied on 4. 5 is left open on the low block. 4 hits 5 with a bounce pass for the layup.",
      "detail": "4 must recognize the counter quickly. 5 should seal immediately after the screen if x3 goes over it.",
      "actions": [
        {
          "type": "cut",
          "player": "5",
          "to": "right_block",
          "bias": "toward_basket"
        },
        {
          "type": "pass",
          "from_player": "4",
          "to_player": "5"
        }
      ]
    }
  ]
} as const;

export const blobBelmontFlash: Play = {
  "name": "BLOB: Belmont Flash (vs 2-3 Zone)",
  "tag": "BLOB",
  "desc": "A baseline out-of-bounds play vs the 2-3 zone. The in-bounder (best shooter) triggers a weak-side flash to pull the middle defender, then curls off a screen to the ball-side corner for an open three. Counter option is a post feed on the low block.",
  "players": {
    "1": [
      -8,
      5
    ],
    "2": [
      0,
      1
    ],
    "3": [
      8,
      5
    ],
    "4": [
      8,
      19
    ],
    "5": [
      -8,
      19
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "2",
  "phases": [
    {
      "label": "Phase 1 – Initial Entry",
      "text": "3 pops out to the right wing to receive the inbound pass from 2. Simultaneously, 1 cuts from the weak-side block up to the top of the key as a safety-valve relay option.",
      "detail": "2 looks to hit 3 immediately on the pop. 1's cut to the top gives a second outlet if 3 is denied.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 8 5 C 7.27 11.93, 9.61 17.59, 15 22",
          "move": {
            "id": "3",
            "to": [
              15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 5 C -9.17 15.14, -6.5 24.14, 0 32",
          "move": {
            "id": "1",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 1 L 15 22",
          "dashed": true,
          "ball": {
            "from": "2",
            "to": "3"
          }
        }
      ]
    },
    {
      "label": "Phase 2 – Weak-Side Flash",
      "text": "On 3's catch, 4 immediately flashes from the right elbow to the high post / middle of the key. 3 passes to 4, drawing the middle zone defender (x5) toward the lane.",
      "detail": "The flash must be sharp and timed to 3's catch. x5 collapsing on 4 is the key that opens the corner.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 8 19 C 4.61 15.55, 1.95 14.22, 0 15",
          "move": {
            "id": "4",
            "to": [
              0,
              15
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 15 22 L 0 15",
          "dashed": true,
          "ball": {
            "from": "3",
            "to": "4"
          }
        }
      ]
    },
    {
      "label": "Phase 3 – Screen & Corner Cut",
      "text": "5 steps across and sets a screen on the ball-side low post defender (x3) at the right block. 2 steps inbounds and curls around 5's screen to the right corner for the catch-and-shoot three. 4 reads the defense and delivers the pass to 2.",
      "detail": "This is the primary scoring action. 4 must read x3: if caught by 5's screen, fire to 2 in the corner.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 19 C -2.67 11.33, 2.67 6.67, 8 5",
          "move": {
            "id": "5",
            "to": [
              8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 1 C 7.5 5.97, 15.5 6.97, 24 4",
          "move": {
            "id": "2",
            "to": [
              24,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 15 L 24 4",
          "dashed": true,
          "ball": {
            "from": "4",
            "to": "2"
          }
        }
      ]
    },
    {
      "label": "Phase 4 – Counter: Post Feed",
      "text": "If x3 fights over 5's screen to contest 2, x5 is already occupied on 4. 5 is left open on the low block. 4 hits 5 with a bounce pass for the layup.",
      "detail": "4 must recognize the counter quickly. 5 should seal immediately after the screen if x3 goes over it.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 8 5 C 8 5, 8 5, 8 5",
          "move": {
            "id": "5",
            "to": [
              8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 15 L 8 5",
          "dashed": true,
          "ball": {
            "from": "4",
            "to": "5"
          }
        }
      ]
    }
  ]
};
