// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "blob-stack-double"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const blobStackDoubleSemantic = {
  "name": "Stack Double (BLOB vs Man-to-Man)",
  "tag": "BLOB",
  "desc": "A BLOB play out of a stack set designed to free the best shooter for an open midrange or three-point shot on the wing. Uses ball reversal, a dribble fake, and a staggered double screen to create separation.",
  "players": {
    "1": "left_elbow",
    "2": "right_elbow",
    "3": "baseline_center",
    "4": "right_slot",
    "5": "right_block"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "3",
  "phases": [
    {
      "label": "Phase 1: Ball Entry to Perimeter",
      "text": "4 pops out to the right wing to receive the inbound pass from 3. Meanwhile, 2 takes steps toward the basket as a decoy to drag their defender away from the perimeter.",
      "actions": [
        {
          "type": "cut",
          "player": "4",
          "to": "right_wing"
        },
        {
          "type": "pass",
          "from_player": "3",
          "to_player": "4"
        }
      ]
    },
    {
      "label": "Phase 2: Ball Reversal to Point Guard",
      "text": "3 sprints the baseline and clears to the weak-side (left) wing. 1 cuts from the left elbow up to the top of the key and receives the reversal pass from 4.",
      "actions": [
        {
          "type": "cut",
          "player": "3",
          "to": "left_wing"
        },
        {
          "type": "cut",
          "player": "1",
          "to": "top_of_key"
        },
        {
          "type": "pass",
          "from_player": "4",
          "to_player": "1"
        }
      ]
    },
    {
      "label": "Phase 3: Dribble Fake to Move Defense",
      "text": "1 takes a dribble away from 2's side (toward the left) to pull defenders toward the middle and open the passing lane to 2 on the right wing. 1 must sell the fake to shift the defense.",
      "actions": [
        {
          "type": "dribble",
          "player": "1",
          "to": "left_slot",
          "bias": "left"
        }
      ]
    },
    {
      "label": "Phase 4: Staggered Screen for Shooter",
      "text": "4 and 5 set a staggered double screen for 2. 2 reads the defense and uses the screens to cut out to the right wing for the shot. 1 delivers the pass to 2 for the midrange or three-point attempt.",
      "actions": [
        {
          "type": "screen",
          "screener": "4",
          "cutter": "2",
          "at": "right_slot",
          "cutter_to": "right_wing"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "2"
        }
      ]
    }
  ]
} as const;

export const blobStackDouble: Play = {
  "name": "Stack Double (BLOB vs Man-to-Man)",
  "tag": "BLOB",
  "desc": "A BLOB play out of a stack set designed to free the best shooter for an open midrange or three-point shot on the wing. Uses ball reversal, a dribble fake, and a staggered double screen to create separation.",
  "players": {
    "1": [
      -8,
      19
    ],
    "2": [
      8,
      19
    ],
    "3": [
      0,
      1
    ],
    "4": [
      13,
      28
    ],
    "5": [
      8,
      5
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "3",
  "phases": [
    {
      "label": "Phase 1: Ball Entry to Perimeter",
      "text": "4 pops out to the right wing to receive the inbound pass from 3. Meanwhile, 2 takes steps toward the basket as a decoy to drag their defender away from the perimeter.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 13 28 C 14.75 26.36, 15.41 24.36, 15 22",
          "move": {
            "id": "4",
            "to": [
              15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 1 L 15 22",
          "dashed": true,
          "ball": {
            "from": "3",
            "to": "4"
          }
        }
      ]
    },
    {
      "label": "Phase 2: Ball Reversal to Point Guard",
      "text": "3 sprints the baseline and clears to the weak-side (left) wing. 1 cuts from the left elbow up to the top of the key and receives the reversal pass from 4.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 1 C -8.25 5.68, -13.25 12.68, -15 22",
          "move": {
            "id": "3",
            "to": [
              -15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 19 C -7.67 24.77, -5.01 29.11, 0 32",
          "move": {
            "id": "1",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 15 22 L 0 32",
          "dashed": true,
          "ball": {
            "from": "4",
            "to": "1"
          }
        }
      ]
    },
    {
      "label": "Phase 3: Dribble Fake to Move Defense",
      "text": "1 takes a dribble away from 2's side (toward the left) to pull defenders toward the middle and open the passing lane to 2 on the right wing. 1 must sell the fake to shift the defense.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 C -5.05 33.01, -9.39 31.67, -13 28",
          "move": {
            "id": "1",
            "to": [
              -13,
              28
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 4: Staggered Screen for Shooter",
      "text": "4 and 5 set a staggered double screen for 2. 2 reads the defense and uses the screens to cut out to the right wing for the shot. 1 delivers the pass to 2 for the midrange or three-point attempt.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 15 22 C 13.42 22.71, 12.75 24.71, 13 28",
          "move": {
            "id": "4",
            "to": [
              13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 19 C 9.79 21.26, 12.13 22.26, 15 22",
          "move": {
            "id": "2",
            "to": [
              15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -13 28 L 15 22",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "2"
          }
        }
      ]
    }
  ]
};
