// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "blob-two-inside"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const blobTwoInsideSemantic = {
  "name": "Two Inside (BLOB vs Man-to-Man)",
  "tag": "BLOB",
  "desc": "A BLOB play targeting dominant post players. Uses an up-screen and screen-the-screener action to free a post player (4) for an open layup at the rim, while guards space the perimeter to prevent help defense from collapsing.",
  "players": {
    "1": "left_elbow",
    "2": "right_elbow",
    "3": "baseline_center",
    "4": "left_block",
    "5": "right_block"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "3",
  "phases": [
    {
      "label": "Phase 1",
      "text": "4 sets an up-screen for 1, who pops out to the left corner. Simultaneously, 2 cuts toward the right slot to call for the ball and keep their defender out of the paint.",
      "detail": "Up-screen by 4 frees 1 to the corner; 2 flashes to the ball-side slot as a decoy and outlet target.",
      "actions": [
        {
          "type": "screen",
          "screener": "4",
          "cutter": "1",
          "at": "left_short_corner",
          "cutter_to": "left_corner"
        },
        {
          "type": "cut",
          "player": "2",
          "to": "right_slot",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 2",
      "text": "5 (who has been facing 2 to disguise the action) cuts across the lane and sets a strong screen on 4's defender. 4 uses the screen to cut hard to the weak-side rim for an open layup. 3 passes to 2 as a primary safety read.",
      "detail": "Screen-the-screener: 5 screens for 4, who cuts to the basket. 3 inbounds to 2 if the pass to 4 is not immediately available.",
      "actions": [
        {
          "type": "screen",
          "screener": "5",
          "cutter": "4",
          "at": "low_post",
          "cutter_to": "left_block"
        },
        {
          "type": "pass",
          "from_player": "3",
          "to_player": "2"
        }
      ]
    },
    {
      "label": "Phase 3",
      "text": "After screening, 5 seals 4's defender and pivots toward the hoop. 2 looks to pass to 4 cutting to the rim; if 4 is denied, 4 backs to the right short corner to open the paint for 5's seal and layup.",
      "detail": "5 seals and flashes to the rim as the second post option; 4 counters to the short corner if covered.",
      "actions": [
        {
          "type": "cut",
          "player": "5",
          "to": "right_block",
          "bias": "toward_basket"
        },
        {
          "type": "pass",
          "from_player": "2",
          "to_player": "5"
        }
      ]
    },
    {
      "label": "Phase 4",
      "text": "If no interior pass is available, 2 passes back over the top or 3 resets by passing to 2, and the team transitions to the half-court offense.",
      "detail": "Safety reset: 2 holds possession and the team organizes into half-court sets.",
      "actions": [
        {
          "type": "cut",
          "player": "4",
          "to": "right_short_corner",
          "bias": "away_from_basket"
        },
        {
          "type": "dribble",
          "player": "2",
          "to": "top_of_key",
          "bias": "away_from_basket"
        }
      ]
    }
  ]
} as const;

export const blobTwoInside: Play = {
  "name": "Two Inside (BLOB vs Man-to-Man)",
  "tag": "BLOB",
  "desc": "A BLOB play targeting dominant post players. Uses an up-screen and screen-the-screener action to free a post player (4) for an open layup at the rim, while guards space the perimeter to prevent help defense from collapsing.",
  "players": {
    "1": [
      -8,
      19
    ],
    "2": [
      8,
      19
    ],
    "3": [
      0,
      1
    ],
    "4": [
      -8,
      5
    ],
    "5": [
      8,
      5
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "3",
  "phases": [
    {
      "label": "Phase 1",
      "text": "4 sets an up-screen for 1, who pops out to the left corner. Simultaneously, 2 cuts toward the right slot to call for the ball and keep their defender out of the paint.",
      "detail": "Up-screen by 4 frees 1 to the corner; 2 flashes to the ball-side slot as a decoy and outlet target.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 5 C -8.66 4.79, -11.32 4.46, -16 4",
          "move": {
            "id": "4",
            "to": [
              -16,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 19 C -10.63 11.12, -15.97 6.12, -24 4",
          "move": {
            "id": "1",
            "to": [
              -24,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 19 C 8.38 19.77, 10.05 22.77, 13 28",
          "move": {
            "id": "2",
            "to": [
              13,
              28
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2",
      "text": "5 (who has been facing 2 to disguise the action) cuts across the lane and sets a strong screen on 4's defender. 4 uses the screen to cut hard to the weak-side rim for an open layup. 3 passes to 2 as a primary safety read.",
      "detail": "Screen-the-screener: 5 screens for 4, who cuts to the basket. 3 inbounds to 2 if the pass to 4 is not immediately available.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 8 5 C 3.32 5.21, 0.66 5.54, 0 6",
          "move": {
            "id": "5",
            "to": [
              0,
              6
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -16 4 L -8 5",
          "move": {
            "id": "4",
            "to": [
              -8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 1 L 13 28",
          "dashed": true,
          "ball": {
            "from": "3",
            "to": "2"
          }
        }
      ]
    },
    {
      "label": "Phase 3",
      "text": "After screening, 5 seals 4's defender and pivots toward the hoop. 2 looks to pass to 4 cutting to the rim; if 4 is denied, 4 backs to the right short corner to open the paint for 5's seal and layup.",
      "detail": "5 seals and flashes to the rim as the second post option; 4 counters to the short corner if covered.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 6 C 0.66 5.54, 3.32 5.21, 8 5",
          "move": {
            "id": "5",
            "to": [
              8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 13 28 L 8 5",
          "dashed": true,
          "ball": {
            "from": "2",
            "to": "5"
          }
        }
      ]
    },
    {
      "label": "Phase 4",
      "text": "If no interior pass is available, 2 passes back over the top or 3 resets by passing to 2, and the team transitions to the half-court offense.",
      "detail": "Safety reset: 2 holds possession and the team organizes into half-court sets.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M -8 5 C 2.95 4.11, 10.95 3.78, 16 4",
          "move": {
            "id": "4",
            "to": [
              16,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 13 28 C 9.43 32.23, 5.1 33.57, 0 32",
          "move": {
            "id": "2",
            "to": [
              0,
              32
            ]
          }
        }
      ]
    }
  ]
};
