// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "blob-flip-updated"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const blobFlipUpdatedSemantic = {
  "name": "BLOB Flip",
  "tag": "BLOB",
  "desc": "A box-formation BLOB play where guards flash to the corners to clear the paint, a cross-screen frees two post players to attack the rim simultaneously from opposite sides, creating a layup opportunity. Safety outlet to the top of the key if both post options are covered.",
  "players": {
    "1": "baseline_center",
    "2": "right_block",
    "3": "left_block",
    "4": "right_elbow",
    "5": "left_elbow"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Guards Clear, Cross Screen Set",
      "text": "1 slaps the ball to start the play. 2 and 3 flash out to the corners to drag their defenders away from the paint and call loudly for the ball. Simultaneously, 5 sets a cross screen on 4's defender at the high post area.",
      "detail": "2 and 3 must call loudly for the basketball even though they likely won't receive it — this drags defenders out of the paint. 5 sets the screen at the correct angle on the back hip of 4's defender.",
      "actions": [
        {
          "type": "cut",
          "player": "2",
          "to": "right_corner"
        },
        {
          "type": "cut",
          "player": "3",
          "to": "left_corner"
        },
        {
          "type": "screen",
          "screener": "5",
          "cutter": "4",
          "at": "high_post",
          "cutter_to": "left_block"
        }
      ]
    },
    {
      "label": "Phase 2 — Dual Rim Attack",
      "text": "4 flashes hard to the ball-side (right) low block calling for the ball. After setting the cross screen, 5 seals 4's defender and flashes to the right block / opposite side of the rim. 1 reads the defense and passes to whichever post player is open for the layup.",
      "detail": "Post players must show target hands. 4 and 5 must stay on their own sides of the lane — if they crowd each other, one defender can cover both passing lanes.",
      "actions": [
        {
          "type": "cut",
          "player": "5",
          "to": "right_block",
          "bias": "toward_basket"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "4"
        }
      ]
    },
    {
      "label": "Phase 3 — Safety Outlet",
      "text": "If neither post player is open, 3 cuts from the left corner to the top of the key to receive a lob pass over the top from 1.",
      "detail": "This outlet resets the offense if the defense successfully takes away both rim-cut options.",
      "actions": [
        {
          "type": "cut",
          "player": "3",
          "to": "top_of_key"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "3"
        }
      ]
    }
  ]
} as const;

export const blobFlipUpdated: Play = {
  "name": "BLOB Flip",
  "tag": "BLOB",
  "desc": "A box-formation BLOB play where guards flash to the corners to clear the paint, a cross-screen frees two post players to attack the rim simultaneously from opposite sides, creating a layup opportunity. Safety outlet to the top of the key if both post options are covered.",
  "players": {
    "1": [
      0,
      1
    ],
    "2": [
      8,
      5
    ],
    "3": [
      -8,
      5
    ],
    "4": [
      8,
      19
    ],
    "5": [
      -8,
      19
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Guards Clear, Cross Screen Set",
      "text": "1 slaps the ball to start the play. 2 and 3 flash out to the corners to drag their defenders away from the paint and call loudly for the ball. Simultaneously, 5 sets a cross screen on 4's defender at the high post area.",
      "detail": "2 and 3 must call loudly for the basketball even though they likely won't receive it — this drags defenders out of the paint. 5 sets the screen at the correct angle on the back hip of 4's defender.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 8 5 L 24 4",
          "move": {
            "id": "2",
            "to": [
              24,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 5 L -24 4",
          "move": {
            "id": "3",
            "to": [
              -24,
              4
            ]
          }
        },
        {
          "marker": "screen",
          "path": "M -8 19 C -4.61 15.55, -1.95 14.22, 0 15",
          "move": {
            "id": "5",
            "to": [
              0,
              15
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 19 C 5.19 11.45, -0.15 6.79, -8 5",
          "move": {
            "id": "4",
            "to": [
              -8,
              5
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2 — Dual Rim Attack",
      "text": "4 flashes hard to the ball-side (right) low block calling for the ball. After setting the cross screen, 5 seals 4's defender and flashes to the right block / opposite side of the rim. 1 reads the defense and passes to whichever post player is open for the layup.",
      "detail": "Post players must show target hands. 4 and 5 must stay on their own sides of the lane — if they crowd each other, one defender can cover both passing lanes.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 15 C 0.73 9.37, 3.4 6.04, 8 5",
          "move": {
            "id": "5",
            "to": [
              8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 1 L -8 5",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "4"
          }
        }
      ]
    },
    {
      "label": "Phase 3 — Safety Outlet",
      "text": "If neither post player is open, 3 cuts from the left corner to the top of the key to receive a lob pass over the top from 1.",
      "detail": "This outlet resets the offense if the defense successfully takes away both rim-cut options.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M -24 4 C -19.04 15.94, -11.04 25.27, 0 32",
          "move": {
            "id": "3",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 1 L 0 32",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "3"
          }
        }
      ]
    }
  ]
};
