// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "blob-stack-man-spread"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const blobStackManSpreadSemantic = {
  "name": "BLOB Stack Man (Spread)",
  "tag": "BLOB",
  "desc": "A simple youth BLOB play from a stack formation. Sequential hard cuts by the first two players spread the defense, leaving the third player open near the block for a pass and quick shot. A top-of-key safety outlet is available if all primary options are covered.",
  "players": {
    "1": "right_elbow",
    "2": "sideline_right_high",
    "3": "right_short_corner",
    "4": "right_block",
    "5": "baseline_right"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "2",
  "phases": [
    {
      "label": "Phase 1 — First Two Cuts",
      "text": "1 blasts hard to the left corner, dragging their defender away from the paint. Simultaneously, 4 cuts hard to the left block (opposite side of the rim), pulling their defender across the lane. Both cuts must be hard and convincing to clear space.",
      "detail": "These two decoy cuts are the engine of the play — neither player is the primary target. 2 should wait patiently and not force the pass to 1.",
      "actions": [
        {
          "type": "cut",
          "player": "1",
          "to": "left_corner",
          "bias": "away_from_basket"
        },
        {
          "type": "cut",
          "player": "4",
          "to": "left_block",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 2 — 3 Steps In for Pass",
      "text": "With 1 and 4's defenders occupied, 3 steps into the vacated space near the ball-side block and receives the inbound pass from 2 for an open shot close to the rim.",
      "detail": "3 is the primary scoring option. 2 now has three potential options: 3 near the block (primary), 4 at the weak-side block (if open layup), or 1 in the corner.",
      "actions": [
        {
          "type": "cut",
          "player": "3",
          "to": "low_post",
          "bias": "toward_basket"
        },
        {
          "type": "pass",
          "from_player": "2",
          "to_player": "3"
        }
      ]
    },
    {
      "label": "Phase 3 — Safety Outlet",
      "text": "If none of the first three options are available, 5 steps out from the baseline to the top of the key to receive the inbound pass from 2 and reset the offense.",
      "detail": "5 is the pressure-release valve — a reliable target to safely inbound the ball and set up a halfcourt possession.",
      "actions": [
        {
          "type": "cut",
          "player": "5",
          "to": "top_of_key",
          "bias": "away_from_basket"
        },
        {
          "type": "pass",
          "from_player": "2",
          "to_player": "5"
        }
      ]
    }
  ]
} as const;

export const blobStackManSpread: Play = {
  "name": "BLOB Stack Man (Spread)",
  "tag": "BLOB",
  "desc": "A simple youth BLOB play from a stack formation. Sequential hard cuts by the first two players spread the defense, leaving the third player open near the block for a pass and quick shot. A top-of-key safety outlet is available if all primary options are covered.",
  "players": {
    "1": [
      8,
      19
    ],
    "2": [
      26,
      25
    ],
    "3": [
      16,
      4
    ],
    "4": [
      8,
      5
    ],
    "5": [
      10,
      1
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "2",
  "phases": [
    {
      "label": "Phase 1 — First Two Cuts",
      "text": "1 blasts hard to the left corner, dragging their defender away from the paint. Simultaneously, 4 cuts hard to the left block (opposite side of the rim), pulling their defender across the lane. Both cuts must be hard and convincing to clear space.",
      "detail": "These two decoy cuts are the engine of the play — neither player is the primary target. 2 should wait patiently and not force the pass to 1.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 8 19 C -5.03 15.85, -15.7 10.85, -24 4",
          "move": {
            "id": "1",
            "to": [
              -24,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 5 C 2.67 8, -2.67 8, -8 5",
          "move": {
            "id": "4",
            "to": [
              -8,
              5
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2 — 3 Steps In for Pass",
      "text": "With 1 and 4's defenders occupied, 3 steps into the vacated space near the ball-side block and receives the inbound pass from 2 for an open shot close to the rim.",
      "detail": "3 is the primary scoring option. 2 now has three potential options: 3 near the block (primary), 4 at the weak-side block (if open layup), or 1 in the corner.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 16 4 C 7.67 4.76, 2.33 5.43, 0 6",
          "move": {
            "id": "3",
            "to": [
              0,
              6
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 26 25 L 0 6",
          "dashed": true,
          "ball": {
            "from": "2",
            "to": "3"
          }
        }
      ]
    },
    {
      "label": "Phase 3 — Safety Outlet",
      "text": "If none of the first three options are available, 5 steps out from the baseline to the top of the key to receive the inbound pass from 2 and reset the offense.",
      "detail": "5 is the pressure-release valve — a reliable target to safely inbound the ball and set up a halfcourt possession.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 10 1 C 7.89 14.07, 4.55 24.41, 0 32",
          "move": {
            "id": "5",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 26 25 L 0 32",
          "dashed": true,
          "ball": {
            "from": "2",
            "to": "5"
          }
        }
      ]
    }
  ]
};
