// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "blob-yo-yo"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const blobYoYoSemantic = {
  "name": "Yo-Yo (BLOB vs Man-to-Man)",
  "tag": "BLOB",
  "desc": "A box-formation BLOB play vs man-to-man. Both guards simultaneously step up and set up-screens for the post players, who cut to the basket for layups. The inbounder reads which post is open and delivers the pass. Includes a safety-valve cut to the wing if both posts are denied.",
  "players": {
    "1": "baseline_center",
    "2": "right_block",
    "3": "left_block",
    "4": "right_elbow",
    "5": "left_elbow"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Guard 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 – Dual Up-Screens",
      "text": "2 and 3 simultaneously step up from the low blocks and set up-screens for 4 and 5. Screeners face each other at the start to disguise the action, then seek out and commit to their screens.",
      "detail": "2 screens for 4 at the right elbow area; 3 screens for 5 at the left elbow area.",
      "actions": [
        {
          "type": "screen",
          "screener": "2",
          "cutter": "4",
          "at": "right_elbow",
          "cutter_to": "right_block",
          "bias": "toward_basket"
        },
        {
          "type": "screen",
          "screener": "3",
          "cutter": "5",
          "at": "left_elbow",
          "cutter_to": "left_block",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 2 – Post Players Explode to Basket",
      "text": "4 and 5 use the screens and cut hard to the basket on their respective sides. They stay separated on their own side of the lane to keep both passing lanes open.",
      "actions": [
        {
          "type": "cut",
          "player": "4",
          "to": "right_short_corner",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "5",
          "to": "left_short_corner",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 3 – Inbounder Reads and Passes",
      "text": "1 reads the defense and delivers the inbound pass to whichever of 4 or 5 is open for the layup finish.",
      "actions": [
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "4"
        }
      ]
    },
    {
      "label": "Phase 4 – Safety Valve",
      "text": "If neither 4 nor 5 is available, 3 cuts from the left elbow area out to the left wing to receive the inbound pass for a midrange shot or to bring the ball up and initiate half-court offense.",
      "actions": [
        {
          "type": "cut",
          "player": "3",
          "to": "left_wing",
          "bias": "away_from_basket"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "3"
        }
      ]
    }
  ]
} as const;

export const blobYoYo: Play = {
  "name": "Yo-Yo (BLOB vs Man-to-Man)",
  "tag": "BLOB",
  "desc": "A box-formation BLOB play vs man-to-man. Both guards simultaneously step up and set up-screens for the post players, who cut to the basket for layups. The inbounder reads which post is open and delivers the pass. Includes a safety-valve cut to the wing if both posts are denied.",
  "players": {
    "1": [
      0,
      1
    ],
    "2": [
      8,
      5
    ],
    "3": [
      -8,
      5
    ],
    "4": [
      8,
      19
    ],
    "5": [
      -8,
      19
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Guard 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 – Dual Up-Screens",
      "text": "2 and 3 simultaneously step up from the low blocks and set up-screens for 4 and 5. Screeners face each other at the start to disguise the action, then seek out and commit to their screens.",
      "detail": "2 screens for 4 at the right elbow area; 3 screens for 5 at the left elbow area.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 8 5 C 5.71 7.73, 5.71 12.4, 8 19",
          "move": {
            "id": "2",
            "to": [
              8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 19 C 5.71 12.4, 5.71 7.73, 8 5",
          "move": {
            "id": "4",
            "to": [
              8,
              5
            ]
          }
        },
        {
          "marker": "screen",
          "path": "M -8 5 C -5.71 7.73, -5.71 12.4, -8 19",
          "move": {
            "id": "3",
            "to": [
              -8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 19 C -5.71 12.4, -5.71 7.73, -8 5",
          "move": {
            "id": "5",
            "to": [
              -8,
              5
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2 – Post Players Explode to Basket",
      "text": "4 and 5 use the screens and cut hard to the basket on their respective sides. They stay separated on their own side of the lane to keep both passing lanes open.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 8 5 C 8.66 4.79, 11.32 4.46, 16 4",
          "move": {
            "id": "4",
            "to": [
              16,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 5 C -8.66 4.79, -11.32 4.46, -16 4",
          "move": {
            "id": "5",
            "to": [
              -16,
              4
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3 – Inbounder Reads and Passes",
      "text": "1 reads the defense and delivers the inbound pass to whichever of 4 or 5 is open for the layup finish.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 1 L 16 4",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "4"
          }
        }
      ]
    },
    {
      "label": "Phase 4 – Safety Valve",
      "text": "If neither 4 nor 5 is available, 3 cuts from the left elbow area out to the left wing to receive the inbound pass for a midrange shot or to bring the ball up and initiate half-court offense.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M -8 19 C -11.48 21.52, -13.81 22.52, -15 22",
          "move": {
            "id": "3",
            "to": [
              -15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 1 L -15 22",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "3"
          }
        }
      ]
    }
  ]
};
