// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "blob-cross"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const blobCrossSemantic = {
  "name": "BLOB: Cross (vs 2-3 Zone)",
  "tag": "BLOB",
  "desc": "Simple baseline out-of-bounds play vs a 2-3 zone. Wings cut to corners to draw bottom defenders wide, then posts cross to opposite low blocks, forcing the zone to cover 4 players with 3 defenders. Inbounder reads and delivers to the open player.",
  "players": {
    "1": "baseline_center",
    "2": "left_wing",
    "3": "right_wing",
    "4": "left_elbow",
    "5": "right_elbow"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Wing 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Corner Cuts",
      "text": "2 and 3 simultaneously cut from their wings to the opposite corners, calling loudly for the ball. This draws both bottom wing zone defenders out wide.",
      "detail": "2 cuts from left wing to left corner; 3 cuts from right wing to right corner. Loud verbal demands create defender uncertainty and pull the zone's bottom two players toward the baseline corners.",
      "actions": [
        {
          "type": "cut",
          "player": "2",
          "to": "left_corner",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "3",
          "to": "right_corner",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 2 — Post Cross",
      "text": "4 and 5 wait a beat, then cross paths and cut hard to the opposite low blocks. With the zone's bottom defenders drawn to the corners, the posts arrive at the blocks unguarded.",
      "detail": "4 crosses from left elbow to right block; 5 crosses from right elbow to left block. The crossing paths create contact and confusion for any remaining zone defenders.",
      "actions": [
        {
          "type": "cut",
          "player": "4",
          "to": "right_block",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "5",
          "to": "left_block",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 3 — Read and Pass",
      "text": "1 reads the defense and inbounds to the open player: a corner shooter (2 or 3) for the three-point attempt, or a post (4 or 5) on the block for a catch-and-finish.",
      "detail": "1 should look weak-side corner first to move the ball-side bottom defender before the posts cross open. Mask the pass direction — do not telegraph with the eyes.",
      "actions": [
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "4"
        }
      ]
    }
  ]
} as const;

export const blobCross: Play = {
  "name": "BLOB: Cross (vs 2-3 Zone)",
  "tag": "BLOB",
  "desc": "Simple baseline out-of-bounds play vs a 2-3 zone. Wings cut to corners to draw bottom defenders wide, then posts cross to opposite low blocks, forcing the zone to cover 4 players with 3 defenders. Inbounder reads and delivers to the open player.",
  "players": {
    "1": [
      0,
      1
    ],
    "2": [
      -15,
      22
    ],
    "3": [
      15,
      22
    ],
    "4": [
      -8,
      19
    ],
    "5": [
      8,
      19
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Wing 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Corner Cuts",
      "text": "2 and 3 simultaneously cut from their wings to the opposite corners, calling loudly for the ball. This draws both bottom wing zone defenders out wide.",
      "detail": "2 cuts from left wing to left corner; 3 cuts from right wing to right corner. Loud verbal demands create defender uncertainty and pull the zone's bottom two players toward the baseline corners.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M -15 22 C -15.21 14.89, -18.21 8.89, -24 4",
          "move": {
            "id": "2",
            "to": [
              -24,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 15 22 C 15.21 14.89, 18.21 8.89, 24 4",
          "move": {
            "id": "3",
            "to": [
              24,
              4
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2 — Post Cross",
      "text": "4 and 5 wait a beat, then cross paths and cut hard to the opposite low blocks. With the zone's bottom defenders drawn to the corners, the posts arrive at the blocks unguarded.",
      "detail": "4 crosses from left elbow to right block; 5 crosses from right elbow to left block. The crossing paths create contact and confusion for any remaining zone defenders.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M -8 19 C -2.67 11.33, 2.67 6.67, 8 5",
          "move": {
            "id": "4",
            "to": [
              8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 19 C 2.67 11.33, -2.67 6.67, -8 5",
          "move": {
            "id": "5",
            "to": [
              -8,
              5
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3 — Read and Pass",
      "text": "1 reads the defense and inbounds to the open player: a corner shooter (2 or 3) for the three-point attempt, or a post (4 or 5) on the block for a catch-and-finish.",
      "detail": "1 should look weak-side corner first to move the ball-side bottom defender before the posts cross open. Mask the pass direction — do not telegraph with the eyes.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 1 L 8 5",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "4"
          }
        }
      ]
    }
  ]
};
