// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "blob-box-gate"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const blobBoxGateSemantic = {
  "name": "Box Gate (BLOB vs Man-to-Man)",
  "tag": "BLOB",
  "desc": "Starting from a box formation, this BLOB play creates three sequential scoring opportunities: a quick layup for the center off a back screen, a catch-and-shoot wing shot for the best shooter off a gate screen, and finally a post-up for the center via a cross screen set by the inbounder.",
  "players": {
    "1": "baseline_right",
    "2": "left_block",
    "3": "right_elbow",
    "4": "left_elbow",
    "5": "right_block"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1",
      "text": "2 sets a back screen for 5, who cuts hard to the rim. 1 looks to throw directly to 5 for the layup. 3 begins drifting up the side of the key but holds until 2 finishes the screen.",
      "detail": "Back screen: 2 moves to screen for 5. 5 cuts to the basket. 1 targets 5 with the inbound pass.",
      "actions": [
        {
          "type": "screen",
          "screener": "2",
          "cutter": "5",
          "at": "low_post",
          "cutter_to": "baseline_center",
          "bias": "toward_basket"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "5"
        }
      ]
    },
    {
      "label": "Phase 2",
      "text": "Immediately after the back screen, 2 sprints off a gate screen formed by 3 and 4. 2 catches the pass on the wing for a catch-and-shoot. 3 and 4 clear to the top of the key after screening.",
      "detail": "Gate screen: 3 and 4 form the gate at the left wing area. 2 curls off the gate to the left wing for the catch-and-shoot. 3 and 4 clear to the top arc.",
      "actions": [
        {
          "type": "screen",
          "screener": "3",
          "cutter": "2",
          "at": "left_slot",
          "cutter_to": "left_wing",
          "bias": "away_from_basket"
        },
        {
          "type": "cut",
          "player": "4",
          "to": "top_of_key",
          "bias": "away_from_basket"
        },
        {
          "type": "pass",
          "from_player": "5",
          "to_player": "2"
        }
      ]
    },
    {
      "label": "Phase 3",
      "text": "1 steps inbounds and sets a cross screen for 5. 5 ducks in or posts up on the ball-side low block. Because 1 is the PG (inbounder), the help defender on the cross screen is smaller, giving 5 a size advantage.",
      "detail": "Cross screen: 1 steps inbounds and screens across for 5. 5 seals the defender and posts up on the right block.",
      "actions": [
        {
          "type": "screen",
          "screener": "1",
          "cutter": "5",
          "at": "high_post",
          "cutter_to": "right_block",
          "bias": "toward_basket"
        },
        {
          "type": "pass",
          "from_player": "2",
          "to_player": "5"
        }
      ]
    }
  ]
} as const;

export const blobBoxGate: Play = {
  "name": "Box Gate (BLOB vs Man-to-Man)",
  "tag": "BLOB",
  "desc": "Starting from a box formation, this BLOB play creates three sequential scoring opportunities: a quick layup for the center off a back screen, a catch-and-shoot wing shot for the best shooter off a gate screen, and finally a post-up for the center via a cross screen set by the inbounder.",
  "players": {
    "1": [
      10,
      1
    ],
    "2": [
      -8,
      5
    ],
    "3": [
      8,
      19
    ],
    "4": [
      -8,
      19
    ],
    "5": [
      8,
      5
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1",
      "text": "2 sets a back screen for 5, who cuts hard to the rim. 1 looks to throw directly to 5 for the layup. 3 begins drifting up the side of the key but holds until 2 finishes the screen.",
      "detail": "Back screen: 2 moves to screen for 5. 5 cuts to the basket. 1 targets 5 with the inbound pass.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 5 C -3.32 5.21, -0.66 5.54, 0 6",
          "move": {
            "id": "2",
            "to": [
              0,
              6
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 5 C 3.38 4.76, 0.72 3.43, 0 1",
          "move": {
            "id": "5",
            "to": [
              0,
              1
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 10 1 L 0 1",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "5"
          }
        }
      ]
    },
    {
      "label": "Phase 2",
      "text": "Immediately after the back screen, 2 sprints off a gate screen formed by 3 and 4. 2 catches the pass on the wing for a catch-and-shoot. 3 and 4 clear to the top of the key after screening.",
      "detail": "Gate screen: 3 and 4 form the gate at the left wing area. 2 curls off the gate to the left wing for the catch-and-shoot. 3 and 4 clear to the top arc.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 8 19 C 1.41 19.03, -5.59 22.03, -13 28",
          "move": {
            "id": "3",
            "to": [
              -13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 6 C -6.95 13.61, -11.95 18.94, -15 22",
          "move": {
            "id": "2",
            "to": [
              -15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 19 C -5.91 26.28, -3.25 30.61, 0 32",
          "move": {
            "id": "4",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 1 L -15 22",
          "dashed": true,
          "ball": {
            "from": "5",
            "to": "2"
          }
        }
      ]
    },
    {
      "label": "Phase 3",
      "text": "1 steps inbounds and sets a cross screen for 5. 5 ducks in or posts up on the ball-side low block. Because 1 is the PG (inbounder), the help defender on the cross screen is smaller, giving 5 a size advantage.",
      "detail": "Cross screen: 1 steps inbounds and screens across for 5. 5 seals the defender and posts up on the right block.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 10 1 C 4.04 4.22, 0.7 8.89, 0 15",
          "move": {
            "id": "1",
            "to": [
              0,
              15
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 1 C 0.72 3.43, 3.38 4.76, 8 5",
          "move": {
            "id": "5",
            "to": [
              8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -15 22 L 8 5",
          "dashed": true,
          "ball": {
            "from": "2",
            "to": "5"
          }
        }
      ]
    }
  ]
};
