// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "blob-two-inside-updated"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const blobTwoInsideUpdatedSemantic = {
  "name": "BLOB Two Inside",
  "tag": "BLOB",
  "desc": "From a box formation, guards clear to safety positions while a screen-the-screener action (up-screen then cross-screen) frees a post player at the rim for an open layup. Best used with dominant post players or size mismatches.",
  "players": {
    "1": "left_elbow",
    "2": "right_elbow",
    "3": "baseline_center",
    "4": "left_block",
    "5": "right_block"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "3",
  "phases": [
    {
      "label": "Phase 1 — Guards Clear, Set Deception",
      "text": "4 sets an up-screen for 1, who pops out to the left corner. Simultaneously, 2 cuts to the right slot calling for the ball, dragging their defender out of the paint. 5 holds position facing 2 to disguise the upcoming screen action.",
      "detail": "1 and 2 must actively call for the ball — even knowing they won't receive it — to occupy defenders and keep the paint clear.",
      "actions": [
        {
          "type": "screen",
          "screener": "4",
          "cutter": "1",
          "at": "left_elbow",
          "cutter_to": "left_corner"
        },
        {
          "type": "cut",
          "player": "2",
          "to": "right_slot",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 2 — Screen-the-Screener Action",
      "text": "5 cuts across the lane and sets a strong cross-screen on 4's defender (screen-the-screener). 4 cuts hard to the weak-side rim area for an open layup. 3 reads the action and delivers the inbound pass to 4.",
      "detail": "5 must time the cross-screen so 4 cuts immediately off it before the defense can recover.",
      "actions": [
        {
          "type": "screen",
          "screener": "5",
          "cutter": "4",
          "at": "right_block",
          "cutter_to": "low_post"
        },
        {
          "type": "pass",
          "from_player": "3",
          "to_player": "4"
        }
      ]
    },
    {
      "label": "Phase 3 — Screener Seals, Secondary Option",
      "text": "After setting the cross-screen, 5 seals 4's defender and pivots toward the basket. If 4's cut is denied, 3 can skip to 5 on the seal. If 5's defender cuts off that pass too, 4 backs out to the short corner to clear the paint for 5's seal move.",
      "detail": "3 must read both post options — the cutting 4 first, then the sealing 5 — before resetting.",
      "actions": [
        {
          "type": "cut",
          "player": "4",
          "to": "left_short_corner",
          "bias": "away_from_basket"
        },
        {
          "type": "pass",
          "from_player": "3",
          "to_player": "5"
        }
      ]
    },
    {
      "label": "Phase 4 — Reset to Half-Court",
      "text": "If no inside options are available, 3 passes over the top to 2 and the team organizes into the half-court offense.",
      "detail": "This reset is the safety valve — 2's positioning in the slot makes them the natural target to re-establish half-court sets.",
      "actions": [
        {
          "type": "pass",
          "from_player": "3",
          "to_player": "2"
        },
        {
          "type": "cut",
          "player": "3",
          "to": "left_slot",
          "bias": "away_from_basket"
        }
      ]
    }
  ]
} as const;

export const blobTwoInsideUpdated: Play = {
  "name": "BLOB Two Inside",
  "tag": "BLOB",
  "desc": "From a box formation, guards clear to safety positions while a screen-the-screener action (up-screen then cross-screen) frees a post player at the rim for an open layup. Best used with dominant post players or size mismatches.",
  "players": {
    "1": [
      -8,
      19
    ],
    "2": [
      8,
      19
    ],
    "3": [
      0,
      1
    ],
    "4": [
      -8,
      5
    ],
    "5": [
      8,
      5
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "3",
  "phases": [
    {
      "label": "Phase 1 — Guards Clear, Set Deception",
      "text": "4 sets an up-screen for 1, who pops out to the left corner. Simultaneously, 2 cuts to the right slot calling for the ball, dragging their defender out of the paint. 5 holds position facing 2 to disguise the upcoming screen action.",
      "detail": "1 and 2 must actively call for the ball — even knowing they won't receive it — to occupy defenders and keep the paint clear.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 5 C -5.71 7.73, -5.71 12.4, -8 19",
          "move": {
            "id": "4",
            "to": [
              -8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 19 C -10.63 11.12, -15.97 6.12, -24 4",
          "move": {
            "id": "1",
            "to": [
              -24,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 19 C 8.38 19.77, 10.05 22.77, 13 28",
          "move": {
            "id": "2",
            "to": [
              13,
              28
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2 — Screen-the-Screener Action",
      "text": "5 cuts across the lane and sets a strong cross-screen on 4's defender (screen-the-screener). 4 cuts hard to the weak-side rim area for an open layup. 3 reads the action and delivers the inbound pass to 4.",
      "detail": "5 must time the cross-screen so 4 cuts immediately off it before the defense can recover.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 8 5 C 8 5, 8 5, 8 5",
          "move": {
            "id": "5",
            "to": [
              8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 19 C -3.88 12.04, -1.22 7.71, 0 6",
          "move": {
            "id": "4",
            "to": [
              0,
              6
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 1 L 0 6",
          "dashed": true,
          "ball": {
            "from": "3",
            "to": "4"
          }
        }
      ]
    },
    {
      "label": "Phase 3 — Screener Seals, Secondary Option",
      "text": "After setting the cross-screen, 5 seals 4's defender and pivots toward the basket. If 4's cut is denied, 3 can skip to 5 on the seal. If 5's defender cuts off that pass too, 4 backs out to the short corner to clear the paint for 5's seal move.",
      "detail": "3 must read both post options — the cutting 4 first, then the sealing 5 — before resetting.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 6 C -8.33 5.24, -13.67 4.57, -16 4",
          "move": {
            "id": "4",
            "to": [
              -16,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 1 L 8 5",
          "dashed": true,
          "ball": {
            "from": "3",
            "to": "5"
          }
        }
      ]
    },
    {
      "label": "Phase 4 — Reset to Half-Court",
      "text": "If no inside options are available, 3 passes over the top to 2 and the team organizes into the half-court offense.",
      "detail": "This reset is the safety valve — 2's positioning in the slot makes them the natural target to re-establish half-court sets.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 1 L 13 28",
          "dashed": true,
          "ball": {
            "from": "3",
            "to": "2"
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 1 C -6.06 12.45, -10.39 21.45, -13 28",
          "move": {
            "id": "3",
            "to": [
              -13,
              28
            ]
          }
        }
      ]
    }
  ]
};
