// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "blob-4-low-flex"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const blob4LowFlexSemantic = {
  "name": "4-Low Flex (BLOB vs Man-to-Man)",
  "tag": "BLOB",
  "desc": "From a 4-low baseline out-of-bounds formation, the ball is passed to the top of the key and the play uses a flex screen followed by a screen-the-screener (pin-down) action. Creates two scoring opportunities: an open layup via the flex cut and a catch-and-shoot from the top of the key.",
  "players": {
    "1": "baseline_right",
    "2": "right_block",
    "3": "left_block",
    "4": "left_short_corner",
    "5": "baseline_left"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "SG"
    },
    "2": {
      "name": "Wing 2",
      "pos": "SF"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Ball to Top of Key",
      "text": "4 cuts up to the top of the key and receives the inbound lob from 1. 3 waits a beat for timing, then cuts to the top of the key to receive the pass from 4.",
      "detail": "Timing is critical — 3 must wait an extra beat before cutting to the top of the key to avoid clogging the lane.",
      "actions": [
        {
          "type": "cut",
          "player": "4",
          "to": "top_of_key"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "4"
        },
        {
          "type": "cut",
          "player": "3",
          "to": "top_arc"
        }
      ]
    },
    {
      "label": "Phase 1b — 4 Passes to 3",
      "text": "4 passes to 3 at the top of the arc. 3 is now the decision-maker.",
      "actions": [
        {
          "type": "pass",
          "from_player": "4",
          "to_player": "3"
        }
      ]
    },
    {
      "label": "Phase 2 — Flex Screen for 5",
      "text": "2 steps inbounds and sets a flex screen across the lane for 5. 5 uses the flex cut to attack the ball-side block, looking for the pass from 3 and an open layup.",
      "detail": "2 must set a strong, legal screen. 5 reads the defense and attacks hard to the ball-side block.",
      "actions": [
        {
          "type": "screen",
          "screener": "2",
          "cutter": "5",
          "at": "left_block",
          "cutter_to": "right_block",
          "bias": "toward_basket"
        },
        {
          "type": "pass",
          "from_player": "3",
          "to_player": "5"
        }
      ]
    },
    {
      "label": "Phase 3 — Screen-the-Screener (Pin Down) for 2",
      "text": "Immediately after 2 sets the flex screen, 4 sets a pin-down screen for 2 (screen-the-screener). 2 cuts off the pin-down to the top of the key for a catch-and-shoot opportunity from 3.",
      "detail": "If 5 is denied on the flex cut, 3 is patient and looks for 2 coming off the pin-down. If both options are covered, 3 resets the offense.",
      "actions": [
        {
          "type": "screen",
          "screener": "4",
          "cutter": "2",
          "at": "left_elbow",
          "cutter_to": "top_of_key",
          "bias": "away_from_basket"
        },
        {
          "type": "pass",
          "from_player": "3",
          "to_player": "2"
        }
      ]
    }
  ]
} as const;

export const blob4LowFlex: Play = {
  "name": "4-Low Flex (BLOB vs Man-to-Man)",
  "tag": "BLOB",
  "desc": "From a 4-low baseline out-of-bounds formation, the ball is passed to the top of the key and the play uses a flex screen followed by a screen-the-screener (pin-down) action. Creates two scoring opportunities: an open layup via the flex cut and a catch-and-shoot from the top of the key.",
  "players": {
    "1": [
      10,
      1
    ],
    "2": [
      8,
      5
    ],
    "3": [
      -8,
      5
    ],
    "4": [
      -16,
      4
    ],
    "5": [
      -10,
      1
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "SG"
    },
    "2": {
      "name": "Wing 2",
      "pos": "SF"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Ball to Top of Key",
      "text": "4 cuts up to the top of the key and receives the inbound lob from 1. 3 waits a beat for timing, then cuts to the top of the key to receive the pass from 4.",
      "detail": "Timing is critical — 3 must wait an extra beat before cutting to the top of the key to avoid clogging the lane.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M -16 4 C -14.14 15.32, -8.81 24.65, 0 32",
          "move": {
            "id": "4",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 10 1 L 0 32",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "4"
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 5 C -8.75 12.77, -6.09 19.11, 0 24",
          "move": {
            "id": "3",
            "to": [
              0,
              24
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 1b — 4 Passes to 3",
      "text": "4 passes to 3 at the top of the arc. 3 is now the decision-maker.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 L 0 24",
          "dashed": true,
          "ball": {
            "from": "4",
            "to": "3"
          }
        }
      ]
    },
    {
      "label": "Phase 2 — Flex Screen for 5",
      "text": "2 steps inbounds and sets a flex screen across the lane for 5. 5 uses the flex cut to attack the ball-side block, looking for the pass from 3 and an open layup.",
      "detail": "2 must set a strong, legal screen. 5 reads the defense and attacks hard to the ball-side block.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 8 5 C 2.67 8, -2.67 8, -8 5",
          "move": {
            "id": "2",
            "to": [
              -8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -10 1 C -2.78 5.07, 3.22 6.41, 8 5",
          "move": {
            "id": "5",
            "to": [
              8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 24 L 8 5",
          "dashed": true,
          "ball": {
            "from": "3",
            "to": "5"
          }
        }
      ]
    },
    {
      "label": "Phase 3 — Screen-the-Screener (Pin Down) for 2",
      "text": "Immediately after 2 sets the flex screen, 4 sets a pin-down screen for 2 (screen-the-screener). 2 cuts off the pin-down to the top of the key for a catch-and-shoot opportunity from 3.",
      "detail": "If 5 is denied on the flex cut, 3 is patient and looks for 2 coming off the pin-down. If both options are covered, 3 resets the offense.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 0 32 C -2.09 24.72, -4.75 20.39, -8 19",
          "move": {
            "id": "4",
            "to": [
              -8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 5 C -6.2 16.87, -3.53 25.87, 0 32",
          "move": {
            "id": "2",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 24 L 0 32",
          "dashed": true,
          "ball": {
            "from": "3",
            "to": "2"
          }
        }
      ]
    }
  ]
};
