// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Registry of plays with extracted SVG coordinate data.
// Add plays by running npm run synthesize; remove by deleting the .ts file and re-running.

import type { Play } from "@/lib/types";
import { play_23Flare } from "./23-flare";
import { play_32Lob } from "./32-lob";
import { blob4LowFlex } from "./blob-4-low-flex";
import { blobBelmontFlash } from "./blob-belmont-flash";
import { blobCross } from "./blob-cross";
import { weaksideFlareSlip } from "./weakside-flare-slip";

export const PLAYS_BY_SLUG: Record<string, Play> = {
  "23-flare": play_23Flare,
  "32-lob": play_32Lob,
  "blob-4-low-flex": blob4LowFlex,
  "blob-belmont-flash": blobBelmontFlash,
  "blob-cross": blobCross,
  "weakside-flare-slip": weaksideFlareSlip,
};

export function getPlayBySlug(slug: string): Play | null {
  return PLAYS_BY_SLUG[slug] ?? null;
}
