// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "play-back-screen-post"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const playBackScreenPostSemantic = {
  "name": "Back Screen Post",
  "tag": "MAN-TO-MAN",
  "desc": "A man-to-man set play combining a staggered screen for the point guard with a surprise back screen to free the post player for a layup or deep block position. Secondary action uses a staggered screen to free the best shooter at the top of the key.",
  "players": {
    "1": "left_wing",
    "2": "left_corner",
    "3": "right_45",
    "4": "right_elbow",
    "5": "left_elbow"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1: Setup",
      "text": "1 dribbles from the left wing up toward the top of the key. 3 walks their defender down to the low block to set up the back screen angle.",
      "detail": "Move defenders into position. Best shooter (2) stays on the same side as best post player (5).",
      "actions": [
        {
          "type": "dribble",
          "player": "1",
          "to": "top_of_key",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "3",
          "to": "right_block",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 2: Staggered Screen for Point Guard",
      "text": "4 and 5 set a staggered screen for 1 as 1 dribbles around the top of the key. This occupies both defenders and opens the full court for 1.",
      "detail": "5 screens first (nearer), then 4 screens second (farther). 1 uses both screens to get a clean look at the full court.",
      "actions": [
        {
          "type": "screen",
          "screener": "5",
          "cutter": "1",
          "at": "left_slot",
          "cutter_to": "right_slot"
        },
        {
          "type": "screen",
          "screener": "4",
          "cutter": "1",
          "at": "high_post",
          "cutter_to": "top_arc"
        }
      ]
    },
    {
      "label": "Phase 3: Surprise Back Screen — Primary Action",
      "text": "As 1 comes off the staggered screens, 3 sprints up and sets a back screen on 5's defender. 5 immediately rolls hard to the basket. 1 looks to pass to 5 for a layup or deep post position.",
      "detail": "Timing is critical — the back screen must happen simultaneously as 1 clears the staggered screens.",
      "actions": [
        {
          "type": "screen",
          "screener": "3",
          "cutter": "5",
          "at": "right_elbow",
          "cutter_to": "low_post",
          "bias": "toward_basket"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "5"
        }
      ]
    },
    {
      "label": "Phase 4: Secondary Action — Staggered Screen for Shooter",
      "text": "If 1 cannot enter the ball to the post, 3 and 4 set a staggered screen for 2, who cuts to the top of the key for an open shot. Alternatively, if 3's defender sags into the key, 3 can pop to the top off a quick screen by 4.",
      "detail": "Read the defense: if post is denied, swing to perimeter shooter coming off staggered screens.",
      "actions": [
        {
          "type": "screen",
          "screener": "4",
          "cutter": "2",
          "at": "left_wing",
          "cutter_to": "left_slot"
        },
        {
          "type": "screen",
          "screener": "3",
          "cutter": "2",
          "at": "left_45",
          "cutter_to": "top_of_key"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "2"
        }
      ]
    }
  ]
} as const;

export const playBackScreenPost: Play = {
  "name": "Back Screen Post",
  "tag": "MAN-TO-MAN",
  "desc": "A man-to-man set play combining a staggered screen for the point guard with a surprise back screen to free the post player for a layup or deep block position. Secondary action uses a staggered screen to free the best shooter at the top of the key.",
  "players": {
    "1": [
      -15,
      22
    ],
    "2": [
      -24,
      4
    ],
    "3": [
      18,
      14
    ],
    "4": [
      8,
      19
    ],
    "5": [
      -8,
      19
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1: Setup",
      "text": "1 dribbles from the left wing up toward the top of the key. 3 walks their defender down to the low block to set up the back screen angle.",
      "detail": "Move defenders into position. Best shooter (2) stays on the same side as best post player (5).",
      "actions": [
        {
          "marker": "arrow",
          "path": "M -15 22 C -9.02 22.5, -4.02 25.83, 0 32",
          "move": {
            "id": "1",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 18 14 C 11.82 10.07, 8.48 7.07, 8 5",
          "move": {
            "id": "3",
            "to": [
              8,
              5
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2: Staggered Screen for Point Guard",
      "text": "4 and 5 set a staggered screen for 1 as 1 dribbles around the top of the key. This occupies both defenders and opens the full court for 1.",
      "detail": "5 screens first (nearer), then 4 screens second (farther). 1 uses both screens to get a clean look at the full court.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 19 C -8.38 19.77, -10.05 22.77, -13 28",
          "move": {
            "id": "5",
            "to": [
              -13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 32 C 5.05 33.01, 9.39 31.67, 13 28",
          "move": {
            "id": "1",
            "to": [
              13,
              28
            ]
          }
        },
        {
          "marker": "screen",
          "path": "M 8 19 C 4.61 15.55, 1.95 14.22, 0 15",
          "move": {
            "id": "4",
            "to": [
              0,
              15
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 13 28 C 9.39 24.33, 5.05 22.99, 0 24",
          "move": {
            "id": "1",
            "to": [
              0,
              24
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3: Surprise Back Screen — Primary Action",
      "text": "As 1 comes off the staggered screens, 3 sprints up and sets a back screen on 5's defender. 5 immediately rolls hard to the basket. 1 looks to pass to 5 for a layup or deep post position.",
      "detail": "Timing is critical — the back screen must happen simultaneously as 1 clears the staggered screens.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 8 5 C 5.71 7.73, 5.71 12.4, 8 19",
          "move": {
            "id": "3",
            "to": [
              8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -13 28 C -7.21 18.04, -2.88 10.71, 0 6",
          "move": {
            "id": "5",
            "to": [
              0,
              6
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 24 L 0 6",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "5"
          }
        }
      ]
    },
    {
      "label": "Phase 4: Secondary Action — Staggered Screen for Shooter",
      "text": "If 1 cannot enter the ball to the post, 3 and 4 set a staggered screen for 2, who cuts to the top of the key for an open shot. Alternatively, if 3's defender sags into the key, 3 can pop to the top off a quick screen by 4.",
      "detail": "Read the defense: if post is denied, swing to perimeter shooter coming off staggered screens.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 0 15 C -3.52 14.72, -8.52 17.06, -15 22",
          "move": {
            "id": "4",
            "to": [
              -15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -24 4 C -23.97 13.67, -20.3 21.67, -13 28",
          "move": {
            "id": "2",
            "to": [
              -13,
              28
            ]
          }
        },
        {
          "marker": "screen",
          "path": "M 8 19 C 0.55 14.59, -8.11 12.93, -18 14",
          "move": {
            "id": "3",
            "to": [
              -18,
              14
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -13 28 C -9.39 31.67, -5.05 33.01, 0 32",
          "move": {
            "id": "2",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 24 L 0 32",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "2"
          }
        }
      ]
    }
  ]
};
