// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "play-iverson-ram"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const playIversonRamSemantic = {
  "name": "Iverson Ram",
  "tag": "offense",
  "desc": "A 1-4 high set play that begins with an Iverson-style wing exchange (both wings crossing simultaneously using elbow screens), then flows into a ram screen action (4 screens 5's defender) before finishing with a pick-and-roll. The ram screen removes the help defender, giving the ball-handler unobstructed space to attack.",
  "players": {
    "1": "top_of_key",
    "2": "left_wing",
    "3": "right_wing",
    "4": "right_elbow",
    "5": "left_elbow"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1: Iverson Wing Exchange",
      "text": "1 opens the angle with a dribble toward the right side. 2 cuts over the top off 4's elbow screen to the right wing. Simultaneously, 3 cuts under off 5's elbow screen to the left wing. 1 passes to 2 coming off 4's screen.",
      "detail": "1's dribble direction is the signal — the side 1 dribbles toward goes under; the opposite side goes over. 2 should look to drive immediately off the catch before the defense recovers.",
      "actions": [
        {
          "type": "screen",
          "screener": "4",
          "cutter": "2",
          "at": "right_elbow",
          "cutter_to": "right_wing",
          "bias": "toward_basket"
        },
        {
          "type": "screen",
          "screener": "5",
          "cutter": "3",
          "at": "left_elbow",
          "cutter_to": "left_wing",
          "bias": "away_from_basket"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "2"
        }
      ]
    },
    {
      "label": "Phase 2: Ram Screen Setup",
      "text": "1 clears to the left corner to create space. 3 rotates down to the right corner. 4 sets a ram (down) screen on 5's defender at the high post. 5 sprints up off 4's screen toward the ball-handler (2) to prepare the on-ball screen.",
      "detail": "4's ram screen removes the helper (x5) from the lane, giving 2 maximum space to operate the pick-and-roll.",
      "actions": [
        {
          "type": "cut",
          "player": "1",
          "to": "left_corner",
          "bias": "away_from_basket"
        },
        {
          "type": "cut",
          "player": "3",
          "to": "right_corner",
          "bias": "away_from_basket"
        },
        {
          "type": "screen",
          "screener": "4",
          "cutter": "5",
          "at": "high_post",
          "cutter_to": "ball_screen_top",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 3: Pick-and-Roll Read",
      "text": "2 dribbles off 5's on-ball screen and makes the best read. With 4 occupying 5's defender, 2 has significant space to attack. Options: drive to the rim, pull-up jumper, pass to 5 rolling, or kick out to a corner.",
      "detail": "5 must sprint to set the on-ball screen. If the defense switches, 5 slips to the rim or seals for a post-up. If 2 is denied, 1 can reverse and run the action to the other side.",
      "actions": [
        {
          "type": "dribble",
          "player": "2",
          "to": "right_slot",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "5",
          "to": "low_post",
          "bias": "toward_basket"
        }
      ]
    }
  ]
} as const;

export const playIversonRam: Play = {
  "name": "Iverson Ram",
  "tag": "offense",
  "desc": "A 1-4 high set play that begins with an Iverson-style wing exchange (both wings crossing simultaneously using elbow screens), then flows into a ram screen action (4 screens 5's defender) before finishing with a pick-and-roll. The ram screen removes the help defender, giving the ball-handler unobstructed space to attack.",
  "players": {
    "1": [
      0,
      32
    ],
    "2": [
      -15,
      22
    ],
    "3": [
      15,
      22
    ],
    "4": [
      8,
      19
    ],
    "5": [
      -8,
      19
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1: Iverson Wing Exchange",
      "text": "1 opens the angle with a dribble toward the right side. 2 cuts over the top off 4's elbow screen to the right wing. Simultaneously, 3 cuts under off 5's elbow screen to the left wing. 1 passes to 2 coming off 4's screen.",
      "detail": "1's dribble direction is the signal — the side 1 dribbles toward goes under; the opposite side goes over. 2 should look to drive immediately off the catch before the defense recovers.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 8 19 C 8 19, 8 19, 8 19",
          "move": {
            "id": "4",
            "to": [
              8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -15 22 C -5 19, 5 19, 15 22",
          "move": {
            "id": "2",
            "to": [
              15,
              22
            ]
          }
        },
        {
          "marker": "screen",
          "path": "M -8 19 C -8 19, -8 19, -8 19",
          "move": {
            "id": "5",
            "to": [
              -8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 15 22 C 5 25, -5 25, -15 22",
          "move": {
            "id": "3",
            "to": [
              -15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 32 L 15 22",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "2"
          }
        }
      ]
    },
    {
      "label": "Phase 2: Ram Screen Setup",
      "text": "1 clears to the left corner to create space. 3 rotates down to the right corner. 4 sets a ram (down) screen on 5's defender at the high post. 5 sprints up off 4's screen toward the ball-handler (2) to prepare the on-ball screen.",
      "detail": "4's ram screen removes the helper (x5) from the lane, giving 2 maximum space to operate the pick-and-roll.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 C -10.06 24.85, -18.06 15.52, -24 4",
          "move": {
            "id": "1",
            "to": [
              -24,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -15 22 C -0.49 18.59, 12.51 12.59, 24 4",
          "move": {
            "id": "3",
            "to": [
              24,
              4
            ]
          }
        },
        {
          "marker": "screen",
          "path": "M 8 19 C 4.61 15.55, 1.95 14.22, 0 15",
          "move": {
            "id": "4",
            "to": [
              0,
              15
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 19 C -4.79 17.93, -2.12 18.93, 0 22",
          "move": {
            "id": "5",
            "to": [
              0,
              22
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3: Pick-and-Roll Read",
      "text": "2 dribbles off 5's on-ball screen and makes the best read. With 4 occupying 5's defender, 2 has significant space to attack. Options: drive to the rim, pull-up jumper, pass to 5 rolling, or kick out to a corner.",
      "detail": "5 must sprint to set the on-ball screen. If the defense switches, 5 slips to the rim or seals for a post-up. If 2 is denied, 1 can reverse and run the action to the other side.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 15 22 C 13.42 22.71, 12.75 24.71, 13 28",
          "move": {
            "id": "2",
            "to": [
              13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 22 C 0 13.67, 0 8.33, 0 6",
          "move": {
            "id": "5",
            "to": [
              0,
              6
            ]
          }
        }
      ]
    }
  ]
};
