// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "play-drive-hammer"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const playDriveHammerSemantic = {
  "name": "Drive Hammer",
  "tag": "PNR",
  "desc": "A box set play designed to get a guard attacking the rim off a quick on-ball screen, with a simultaneous hammer (back) screen for a corner shooter and an additional corner passing option. The defense is forced to choose between stopping the drive, helping on the roll, or leaving a corner shooter open.",
  "players": {
    "1": "top_of_key",
    "2": "right_block",
    "3": "left_block",
    "4": "left_elbow",
    "5": "right_elbow"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1: Wing Entry & Setup",
      "text": "1 dribbles to the left wing. 4 sets a screen at the left elbow for 3, who cuts high to receive the entry pass from 1. Simultaneously, 2 relocates from the weak-side block out to the right corner for spacing.",
      "actions": [
        {
          "type": "dribble",
          "player": "1",
          "to": "left_wing"
        },
        {
          "type": "screen",
          "screener": "4",
          "cutter": "3",
          "at": "left_elbow",
          "cutter_to": "left_slot"
        },
        {
          "type": "cut",
          "player": "2",
          "to": "right_corner"
        }
      ]
    },
    {
      "label": "Phase 1b: Wing Pass to 3",
      "text": "1 passes to 3, who has popped off 4's screen. 1 then relocates to the left corner, setting up for the hammer screen.",
      "actions": [
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "3"
        },
        {
          "type": "cut",
          "player": "1",
          "to": "left_corner"
        }
      ]
    },
    {
      "label": "Phase 2: On-Ball Screen & Hammer Action",
      "text": "On 3's catch, 5 immediately steps up and sets an on-ball screen. Simultaneously, 4 sets a hammer (back) screen on 1's defender to free 1 in the corner. 3 uses the ball screen and attacks the rim.",
      "actions": [
        {
          "type": "screen",
          "screener": "5",
          "cutter": "3",
          "at": "left_slot",
          "cutter_to": "low_post",
          "bias": "toward_basket"
        },
        {
          "type": "screen",
          "screener": "4",
          "cutter": "1",
          "at": "left_short_corner",
          "cutter_to": "left_corner"
        }
      ]
    },
    {
      "label": "Phase 3: Read & Finish",
      "text": "3 attacks the rim. If x2 helps on the drive, 3 kicks out to 2 in the right corner. If x1 is caught by the hammer screen, 3 hits 1 in the left corner. 5 rolls to the rim if the defense switches.",
      "actions": [
        {
          "type": "pass",
          "from_player": "3",
          "to_player": "2"
        }
      ]
    }
  ]
} as const;

export const playDriveHammer: Play = {
  "name": "Drive Hammer",
  "tag": "PNR",
  "desc": "A box set play designed to get a guard attacking the rim off a quick on-ball screen, with a simultaneous hammer (back) screen for a corner shooter and an additional corner passing option. The defense is forced to choose between stopping the drive, helping on the roll, or leaving a corner shooter open.",
  "players": {
    "1": [
      0,
      32
    ],
    "2": [
      8,
      5
    ],
    "3": [
      -8,
      5
    ],
    "4": [
      -8,
      19
    ],
    "5": [
      8,
      19
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1: Wing Entry & Setup",
      "text": "1 dribbles to the left wing. 4 sets a screen at the left elbow for 3, who cuts high to receive the entry pass from 1. Simultaneously, 2 relocates from the weak-side block out to the right corner for spacing.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 L -15 22",
          "move": {
            "id": "1",
            "to": [
              -15,
              22
            ]
          }
        },
        {
          "marker": "screen",
          "path": "M -8 19 C -8 19, -8 19, -8 19",
          "move": {
            "id": "4",
            "to": [
              -8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 5 C -13.58 11.82, -15.24 19.48, -13 28",
          "move": {
            "id": "3",
            "to": [
              -13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 5 L 24 4",
          "move": {
            "id": "2",
            "to": [
              24,
              4
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 1b: Wing Pass to 3",
      "text": "1 passes to 3, who has popped off 4's screen. 1 then relocates to the left corner, setting up for the hammer screen.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M -15 22 L -13 28",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "3"
          }
        },
        {
          "marker": "arrow",
          "path": "M -15 22 C -14.76 14.38, -17.76 8.38, -24 4",
          "move": {
            "id": "1",
            "to": [
              -24,
              4
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2: On-Ball Screen & Hammer Action",
      "text": "On 3's catch, 5 immediately steps up and sets an on-ball screen. Simultaneously, 4 sets a hammer (back) screen on 1's defender to free 1 in the corner. 3 uses the ball screen and attacks the rim.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 8 19 C 1.41 19.03, -5.59 22.03, -13 28",
          "move": {
            "id": "5",
            "to": [
              -13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -13 28 C -7.21 18.04, -2.88 10.71, 0 6",
          "move": {
            "id": "3",
            "to": [
              0,
              6
            ]
          }
        },
        {
          "marker": "screen",
          "path": "M -8 19 C -8.01 12.61, -10.67 7.61, -16 4",
          "move": {
            "id": "4",
            "to": [
              -16,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -24 4 C -24 4, -24 4, -24 4",
          "move": {
            "id": "1",
            "to": [
              -24,
              4
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3: Read & Finish",
      "text": "3 attacks the rim. If x2 helps on the drive, 3 kicks out to 2 in the right corner. If x1 is caught by the hammer screen, 3 hits 1 in the left corner. 5 rolls to the rim if the defense switches.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 6 L 24 4",
          "dashed": true,
          "ball": {
            "from": "3",
            "to": "2"
          }
        }
      ]
    }
  ]
};
