// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "play-pick-and-roll-layered"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const playPickAndRollLayeredSemantic = {
  "name": "Motion Offense Pick-and-Roll Play",
  "tag": "Half-Court",
  "desc": "A layered half-court play from a two-guards/two-posts box set. Phase 1: Guard 2 uses a high-post rub screen from Post 4 and posts up. Phase 2: Post 4 leaves the elbow to set a side pick-and-roll for Guard 1. Phase 3: Post 5 and Wing 3 set a perpendicular double screen on the baseline for Guard 2 to curl off. Three sequential scoring threats with four reads for the point guard.",
  "players": {
    "1": "left_wing",
    "2": "left_slot",
    "3": "right_wing",
    "4": "left_elbow",
    "5": "right_elbow"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1: High-Post Rub Cut",
      "text": "Guard 1 dribbles on the left side. Guard 2 uses Post 4's high-post rub screen at the left elbow and cuts down to post up on the left block. Guard 1 reads the pass to Guard 2 in the low post or continues.",
      "detail": "4 sets the screen at the left elbow; 2 rubs off it and dives to the left block. 1 stays left wing with the ball.",
      "actions": [
        {
          "type": "screen",
          "screener": "4",
          "cutter": "2",
          "at": "left_elbow",
          "cutter_to": "left_block"
        },
        {
          "type": "dribble",
          "player": "1",
          "to": "left_wing",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 2: Side Screen / Pick-and-Roll for Guard 1",
      "text": "Post 4 leaves the elbow and sets a side screen for Guard 1 on the left wing. Guard 1 runs the pick-and-roll off the screen. Post 4 rolls to the basket (or flares) based on defensive reaction.",
      "detail": "4 sets the side pick at the left slot area; 1 dribbles off the screen toward the middle. 4 rolls hard to the basket. Guard 2 holds on the left block.",
      "actions": [
        {
          "type": "screen",
          "screener": "4",
          "cutter": "1",
          "at": "left_slot",
          "cutter_to": "top_of_key",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "4",
          "to": "low_post",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 3: Perpendicular Double Screen for Guard 2",
      "text": "Post 5 and Wing 3 set a perpendicular double screen on the right baseline. Guard 2 cuts off the double screen from the left block toward the right corner. Guard 1 now reads four options: pass to Post 4 (roll/flare), Guard 2 (off double screen), Post 5 (slipping), or Wing 3 (popping). Depicted pass targets Post 4 rolling.",
      "detail": "5 and 3 form the double screen at the right baseline. 2 cuts from left block off the double screen to the right corner. 1 is at top of key with the ball choosing the best read.",
      "actions": [
        {
          "type": "screen",
          "screener": "5",
          "cutter": "2",
          "at": "right_short_corner",
          "cutter_to": "right_corner"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "4"
        }
      ]
    }
  ]
} as const;

export const playPickAndRollLayered: Play = {
  "name": "Motion Offense Pick-and-Roll Play",
  "tag": "Half-Court",
  "desc": "A layered half-court play from a two-guards/two-posts box set. Phase 1: Guard 2 uses a high-post rub screen from Post 4 and posts up. Phase 2: Post 4 leaves the elbow to set a side pick-and-roll for Guard 1. Phase 3: Post 5 and Wing 3 set a perpendicular double screen on the baseline for Guard 2 to curl off. Three sequential scoring threats with four reads for the point guard.",
  "players": {
    "1": [
      -15,
      22
    ],
    "2": [
      -13,
      28
    ],
    "3": [
      15,
      22
    ],
    "4": [
      -8,
      19
    ],
    "5": [
      8,
      19
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1: High-Post Rub Cut",
      "text": "Guard 1 dribbles on the left side. Guard 2 uses Post 4's high-post rub screen at the left elbow and cuts down to post up on the left block. Guard 1 reads the pass to Guard 2 in the low post or continues.",
      "detail": "4 sets the screen at the left elbow; 2 rubs off it and dives to the left block. 1 stays left wing with the ball.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 19 C -8 19, -8 19, -8 19",
          "move": {
            "id": "4",
            "to": [
              -8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -13 28 C -7.42 21.18, -5.76 13.52, -8 5",
          "move": {
            "id": "2",
            "to": [
              -8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -15 22 C -15 22, -15 22, -15 22",
          "move": {
            "id": "1",
            "to": [
              -15,
              22
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2: Side Screen / Pick-and-Roll for Guard 1",
      "text": "Post 4 leaves the elbow and sets a side screen for Guard 1 on the left wing. Guard 1 runs the pick-and-roll off the screen. Post 4 rolls to the basket (or flares) based on defensive reaction.",
      "detail": "4 sets the side pick at the left slot area; 1 dribbles off the screen toward the middle. 4 rolls hard to the basket. Guard 2 holds on the left block.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 19 C -8.38 19.77, -10.05 22.77, -13 28",
          "move": {
            "id": "4",
            "to": [
              -13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -15 22 C -9.02 22.5, -4.02 25.83, 0 32",
          "move": {
            "id": "1",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -13 28 C -7.21 18.04, -2.88 10.71, 0 6",
          "move": {
            "id": "4",
            "to": [
              0,
              6
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3: Perpendicular Double Screen for Guard 2",
      "text": "Post 5 and Wing 3 set a perpendicular double screen on the right baseline. Guard 2 cuts off the double screen from the left block toward the right corner. Guard 1 now reads four options: pass to Post 4 (roll/flare), Guard 2 (off double screen), Post 5 (slipping), or Wing 3 (popping). Depicted pass targets Post 4 rolling.",
      "detail": "5 and 3 form the double screen at the right baseline. 2 cuts from left block off the double screen to the right corner. 1 is at top of key with the ball choosing the best read.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 8 19 C 8.01 12.61, 10.67 7.61, 16 4",
          "move": {
            "id": "5",
            "to": [
              16,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 5 L 24 4",
          "move": {
            "id": "2",
            "to": [
              24,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 32 L 0 6",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "4"
          }
        }
      ]
    }
  ]
};
