// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "play-deception-slob"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const playDeceptionSlobSemantic = {
  "name": "Deception (SLOB)",
  "tag": "SLOB",
  "desc": "A SLOB play from a modified box set that creates a simultaneous backdoor layup for the inbounder and a three-point opportunity for the best shooter. 4 screens for 1 to receive the inbound, then 5 screens for 2 cutting to the top while 4 screens for 3 cutting backdoor — giving 1 a two-pronged decision.",
  "players": {
    "1": "left_elbow",
    "2": "right_wing",
    "3": "sideline_left_high",
    "4": "left_block",
    "5": "right_block"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Wing 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "3",
  "phases": [
    {
      "label": "Phase 1 — Inbound Entry",
      "text": "4 sets a down screen for 1, who pops to the top of the key. 3 inbounds to 1.",
      "detail": "4 screens down freeing 1 to receive the inbound pass safely at the top of the key.",
      "actions": [
        {
          "type": "screen",
          "screener": "4",
          "cutter": "1",
          "at": "left_slot",
          "cutter_to": "top_of_key"
        },
        {
          "type": "pass",
          "from_player": "3",
          "to_player": "1"
        }
      ]
    },
    {
      "label": "Phase 2 — Two-Pronged Attack",
      "text": "5 sprints to screen 2's defender; 2 cuts to the top arc for a three. Simultaneously, 4 screens for 3, who takes a step toward the ball then cuts hard backdoor to the basket.",
      "detail": "Both actions trigger the moment 1 catches the inbound. 5 must wait for the catch before screening so 2 does not cut early.",
      "actions": [
        {
          "type": "screen",
          "screener": "5",
          "cutter": "2",
          "at": "right_slot",
          "cutter_to": "top_arc"
        },
        {
          "type": "screen",
          "screener": "4",
          "cutter": "3",
          "at": "left_wing",
          "cutter_to": "left_block",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 3 — Decision Pass",
      "text": "1 reads the defense and delivers the correct pass: to 2 at the top arc for a three, or to 3 cutting backdoor for a layup.",
      "detail": "If both options are denied, 4 can flash to the elbow as a safety valve.",
      "actions": [
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "2"
        }
      ]
    }
  ]
} as const;

export const playDeceptionSlob: Play = {
  "name": "Deception (SLOB)",
  "tag": "SLOB",
  "desc": "A SLOB play from a modified box set that creates a simultaneous backdoor layup for the inbounder and a three-point opportunity for the best shooter. 4 screens for 1 to receive the inbound, then 5 screens for 2 cutting to the top while 4 screens for 3 cutting backdoor — giving 1 a two-pronged decision.",
  "players": {
    "1": [
      -8,
      19
    ],
    "2": [
      15,
      22
    ],
    "3": [
      -26,
      25
    ],
    "4": [
      -8,
      5
    ],
    "5": [
      8,
      5
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Wing 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "3",
  "phases": [
    {
      "label": "Phase 1 — Inbound Entry",
      "text": "4 sets a down screen for 1, who pops to the top of the key. 3 inbounds to 1.",
      "detail": "4 screens down freeing 1 to receive the inbound pass safely at the top of the key.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 5 C -7.62 10.47, -9.29 18.14, -13 28",
          "move": {
            "id": "4",
            "to": [
              -13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 19 C -7.67 24.77, -5.01 29.11, 0 32",
          "move": {
            "id": "1",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -26 25 L 0 32",
          "dashed": true,
          "ball": {
            "from": "3",
            "to": "1"
          }
        }
      ]
    },
    {
      "label": "Phase 2 — Two-Pronged Attack",
      "text": "5 sprints to screen 2's defender; 2 cuts to the top arc for a three. Simultaneously, 4 screens for 3, who takes a step toward the ball then cuts hard backdoor to the basket.",
      "detail": "Both actions trigger the moment 1 catches the inbound. 5 must wait for the catch before screening so 2 does not cut early.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 8 5 C 7.62 10.47, 9.29 18.14, 13 28",
          "move": {
            "id": "5",
            "to": [
              13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 15 22 C 9.64 19.97, 4.64 20.63, 0 24",
          "move": {
            "id": "2",
            "to": [
              0,
              24
            ]
          }
        },
        {
          "marker": "screen",
          "path": "M -13 28 C -12.75 24.71, -13.42 22.71, -15 22",
          "move": {
            "id": "4",
            "to": [
              -15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -26 25 C -17.4 16.84, -11.4 10.17, -8 5",
          "move": {
            "id": "3",
            "to": [
              -8,
              5
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3 — Decision Pass",
      "text": "1 reads the defense and delivers the correct pass: to 2 at the top arc for a three, or to 3 cutting backdoor for a layup.",
      "detail": "If both options are denied, 4 can flash to the elbow as a safety valve.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 L 0 24",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "2"
          }
        }
      ]
    }
  ]
};
