// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "play-diamond-slob"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const playDiamondSlobSemantic = {
  "name": "Diamond (SLOB)",
  "tag": "SLOB",
  "desc": "A multi-option SLOB play from a box formation. Options include a curl off a screen, a flare screen for a three-point shooter, and a pick-and-roll at the top of the key. Best for teams with an elite playmaker surrounded by shooters.",
  "players": {
    "1": "left_block",
    "2": "right_block",
    "3": "sideline_left_high",
    "4": "right_elbow",
    "5": "left_elbow"
  },
  "roster": {
    "1": {
      "name": "Shooter 1",
      "pos": "SG"
    },
    "2": {
      "name": "Playmaker 2",
      "pos": "PG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "3",
  "phases": [
    {
      "label": "Phase 1",
      "text": "5 sets a down screen for 1, who cuts to the top of the key to receive the inbound pass from 3. 4 then sets a down screen for 2, who pops to the wing.",
      "detail": "After the inbound, 4 sets a down screen for 2, who uses it to pop to the left wing. 1 passes to 2.",
      "actions": [
        {
          "type": "screen",
          "screener": "5",
          "cutter": "1",
          "at": "left_slot",
          "cutter_to": "top_of_key"
        },
        {
          "type": "pass",
          "from_player": "3",
          "to_player": "1"
        }
      ]
    },
    {
      "label": "Phase 1b",
      "text": "4 sets a down screen for 2, who pops out to the right wing. 1 passes to 2.",
      "actions": [
        {
          "type": "screen",
          "screener": "4",
          "cutter": "2",
          "at": "right_slot",
          "cutter_to": "right_wing"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "2"
        }
      ]
    },
    {
      "label": "Phase 2",
      "text": "3 (inbounder) cuts baseline off a screen from 4, curling toward the right short corner for a potential pass. Simultaneously, 5 sets a flare screen for 1, who flares to the left wing for a skip pass from 2.",
      "actions": [
        {
          "type": "screen",
          "screener": "5",
          "cutter": "1",
          "at": "high_post",
          "cutter_to": "left_wing"
        },
        {
          "type": "cut",
          "player": "3",
          "to": "right_short_corner",
          "bias": "toward_basket"
        },
        {
          "type": "pass",
          "from_player": "2",
          "to_player": "1"
        }
      ]
    },
    {
      "label": "Phase 3",
      "text": "If the skip pass to 1 is unavailable, 5 sets an on-ball screen for 2 at the top of the key. 2 uses the pick-and-roll to attack the rim, with options to shoot, pass to 4 (roll/pop), or kick out to 1.",
      "actions": [
        {
          "type": "screen",
          "screener": "5",
          "cutter": "2",
          "at": "ball_screen_top",
          "cutter_to": "left_slot"
        },
        {
          "type": "dribble",
          "player": "2",
          "to": "high_post",
          "bias": "toward_basket"
        }
      ]
    }
  ]
} as const;

export const playDiamondSlob: Play = {
  "name": "Diamond (SLOB)",
  "tag": "SLOB",
  "desc": "A multi-option SLOB play from a box formation. Options include a curl off a screen, a flare screen for a three-point shooter, and a pick-and-roll at the top of the key. Best for teams with an elite playmaker surrounded by shooters.",
  "players": {
    "1": [
      -8,
      5
    ],
    "2": [
      8,
      5
    ],
    "3": [
      -26,
      25
    ],
    "4": [
      8,
      19
    ],
    "5": [
      -8,
      19
    ]
  },
  "roster": {
    "1": {
      "name": "Shooter 1",
      "pos": "SG"
    },
    "2": {
      "name": "Playmaker 2",
      "pos": "PG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "3",
  "phases": [
    {
      "label": "Phase 1",
      "text": "5 sets a down screen for 1, who cuts to the top of the key to receive the inbound pass from 3. 4 then sets a down screen for 2, who pops to the wing.",
      "detail": "After the inbound, 4 sets a down screen for 2, who uses it to pop to the left wing. 1 passes to 2.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 19 C -8.38 19.77, -10.05 22.77, -13 28",
          "move": {
            "id": "5",
            "to": [
              -13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 5 C -9.17 15.14, -6.5 24.14, 0 32",
          "move": {
            "id": "1",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -26 25 L 0 32",
          "dashed": true,
          "ball": {
            "from": "3",
            "to": "1"
          }
        }
      ]
    },
    {
      "label": "Phase 1b",
      "text": "4 sets a down screen for 2, who pops out to the right wing. 1 passes to 2.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 8 19 C 8.38 19.77, 10.05 22.77, 13 28",
          "move": {
            "id": "4",
            "to": [
              13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 5 C 7.27 11.93, 9.61 17.59, 15 22",
          "move": {
            "id": "2",
            "to": [
              15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 32 L 15 22",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "2"
          }
        }
      ]
    },
    {
      "label": "Phase 2",
      "text": "3 (inbounder) cuts baseline off a screen from 4, curling toward the right short corner for a potential pass. Simultaneously, 5 sets a flare screen for 1, who flares to the left wing for a skip pass from 2.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -13 28 C -7.55 20.88, -3.22 16.55, 0 15",
          "move": {
            "id": "5",
            "to": [
              0,
              15
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 32 C -3.2 25.97, -8.2 22.63, -15 22",
          "move": {
            "id": "1",
            "to": [
              -15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -26 25 C -10.57 15.36, 3.43 8.36, 16 4",
          "move": {
            "id": "3",
            "to": [
              16,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 15 22 L -15 22",
          "dashed": true,
          "ball": {
            "from": "2",
            "to": "1"
          }
        }
      ]
    },
    {
      "label": "Phase 3",
      "text": "If the skip pass to 1 is unavailable, 5 sets an on-ball screen for 2 at the top of the key. 2 uses the pick-and-roll to attack the rim, with options to shoot, pass to 4 (roll/pop), or kick out to 1.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 0 15 C 0 15.58, 0 17.92, 0 22",
          "move": {
            "id": "5",
            "to": [
              0,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 15 22 C 4.83 20.09, -4.5 22.09, -13 28",
          "move": {
            "id": "2",
            "to": [
              -13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -13 28 C -7.55 20.88, -3.22 16.55, 0 15",
          "move": {
            "id": "2",
            "to": [
              0,
              15
            ]
          }
        }
      ]
    }
  ]
};
