// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "play-prowl-slob"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const playProwlSlobSemantic = {
  "name": "Prowl (SLOB)",
  "tag": "SLOB",
  "desc": "A quick SLOB play from a box formation. Simultaneous down screens get the ball to the top of the key, then 5 immediately sprints up to set an on-ball screen for 2 in a pick-and-roll attack. Floor spacing from 1 and 3 on the wings and 4 rolling creates 2-on-1 opportunities.",
  "players": {
    "1": "sideline_left_high",
    "2": "left_elbow",
    "3": "right_elbow",
    "4": "left_block",
    "5": "right_block"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Simultaneous Down Screens",
      "text": "4 and 5 set simultaneous down screens for 2 and 3. 2 cuts to the top of the key to receive the inbound pass from 1. 3 pops to the weak-side (right) wing for floor spacing.",
      "detail": "Both post players screen at the same time, forcing the defense to make multiple decisions. 2 is the primary target at the top; 3's pop is a safety valve and spacing threat.",
      "actions": [
        {
          "type": "screen",
          "screener": "4",
          "cutter": "2",
          "at": "left_elbow",
          "cutter_to": "top_of_key"
        },
        {
          "type": "screen",
          "screener": "5",
          "cutter": "3",
          "at": "right_elbow",
          "cutter_to": "right_wing"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "2"
        }
      ]
    },
    {
      "label": "Phase 2 — Inbounder Enters; Pick-and-Roll",
      "text": "After inbounding, 1 steps onto the floor to the ball-side (left) wing. 5 sprints up and sets an on-ball screen for 2 at the top of the key. 2 uses the screen and attacks the rim.",
      "detail": "5 must screen at the correct angle and explode into the screen to prevent the defender from hedging. 1 filling the left wing maintains four-around-one floor spacing for the PnR.",
      "actions": [
        {
          "type": "cut",
          "player": "1",
          "to": "left_wing"
        },
        {
          "type": "screen",
          "screener": "5",
          "cutter": "2",
          "at": "ball_screen_top",
          "cutter_to": "high_post"
        }
      ]
    },
    {
      "label": "Phase 3 — PnR Read",
      "text": "Option A: 2 finishes at the basket. Option B: If 4's defender steps up to help on 2's drive, 2 drops the pass to 4 rolling for the finish. 1 and 3 remain on the wings as kick-out safety valves.",
      "detail": "2 must read the defense: if 4's defender helps, pass; if not, finish at the rim. 1 and 3 on the wings stretch the floor and provide reset options if both primary reads are covered.",
      "actions": [
        {
          "type": "cut",
          "player": "2",
          "to": "low_post",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "5",
          "to": "right_block",
          "bias": "toward_basket"
        }
      ]
    }
  ]
} as const;

export const playProwlSlob: Play = {
  "name": "Prowl (SLOB)",
  "tag": "SLOB",
  "desc": "A quick SLOB play from a box formation. Simultaneous down screens get the ball to the top of the key, then 5 immediately sprints up to set an on-ball screen for 2 in a pick-and-roll attack. Floor spacing from 1 and 3 on the wings and 4 rolling creates 2-on-1 opportunities.",
  "players": {
    "1": [
      -26,
      25
    ],
    "2": [
      -8,
      19
    ],
    "3": [
      8,
      19
    ],
    "4": [
      -8,
      5
    ],
    "5": [
      8,
      5
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Simultaneous Down Screens",
      "text": "4 and 5 set simultaneous down screens for 2 and 3. 2 cuts to the top of the key to receive the inbound pass from 1. 3 pops to the weak-side (right) wing for floor spacing.",
      "detail": "Both post players screen at the same time, forcing the defense to make multiple decisions. 2 is the primary target at the top; 3's pop is a safety valve and spacing threat.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 5 C -5.71 7.73, -5.71 12.4, -8 19",
          "move": {
            "id": "4",
            "to": [
              -8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 19 C -7.67 24.77, -5.01 29.11, 0 32",
          "move": {
            "id": "2",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "screen",
          "path": "M 8 5 C 5.71 7.73, 5.71 12.4, 8 19",
          "move": {
            "id": "5",
            "to": [
              8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 19 C 9.79 21.26, 12.13 22.26, 15 22",
          "move": {
            "id": "3",
            "to": [
              15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -26 25 L 0 32",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "2"
          }
        }
      ]
    },
    {
      "label": "Phase 2 — Inbounder Enters; Pick-and-Roll",
      "text": "After inbounding, 1 steps onto the floor to the ball-side (left) wing. 5 sprints up and sets an on-ball screen for 2 at the top of the key. 2 uses the screen and attacks the rim.",
      "detail": "5 must screen at the correct angle and explode into the screen to prevent the defender from hedging. 1 filling the left wing maintains four-around-one floor spacing for the PnR.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M -26 25 C -21.79 25.98, -18.13 24.98, -15 22",
          "move": {
            "id": "1",
            "to": [
              -15,
              22
            ]
          }
        },
        {
          "marker": "screen",
          "path": "M 8 19 C 4.79 17.93, 2.12 18.93, 0 22",
          "move": {
            "id": "5",
            "to": [
              0,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 32 C 3.06 26.33, 3.06 20.67, 0 15",
          "move": {
            "id": "2",
            "to": [
              0,
              15
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3 — PnR Read",
      "text": "Option A: 2 finishes at the basket. Option B: If 4's defender steps up to help on 2's drive, 2 drops the pass to 4 rolling for the finish. 1 and 3 remain on the wings as kick-out safety valves.",
      "detail": "2 must read the defense: if 4's defender helps, pass; if not, finish at the rim. 1 and 3 on the wings stretch the floor and provide reset options if both primary reads are covered.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 15 C 0 9.75, 0 6.75, 0 6",
          "move": {
            "id": "2",
            "to": [
              0,
              6
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 22 C 1.36 13.63, 4.02 7.97, 8 5",
          "move": {
            "id": "5",
            "to": [
              8,
              5
            ]
          }
        }
      ]
    }
  ]
};
