// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "play-box-loop-post"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const playBoxLoopPostSemantic = {
  "name": "Box Loop Post",
  "tag": "SLOB",
  "desc": "A SLOB play from a box set using sequential down screens to isolate the best post player (4) at the high post for a 1-on-1 opportunity. 5 screens for 1 to get the ball in, then 4 screens for 2 to clear help defenders, before sealing at the high post for a pass from 1.",
  "players": {
    "1": "left_elbow",
    "2": "right_elbow",
    "3": "sideline_left_high",
    "4": "right_block",
    "5": "left_block"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Wing 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "3",
  "phases": [
    {
      "label": "Phase 1",
      "text": "5 sets a down screen for 1, who cuts to the top of the key. 3 inbounds the ball to 1. 5 holds below the block after screening. 3 steps onto the court.",
      "detail": "The down screen by 5 frees 1 at the top of the key to receive the inbound pass cleanly.",
      "actions": [
        {
          "type": "screen",
          "screener": "5",
          "cutter": "1",
          "at": "left_elbow",
          "cutter_to": "top_of_key"
        },
        {
          "type": "pass",
          "from_player": "3",
          "to_player": "1"
        }
      ]
    },
    {
      "label": "Phase 2",
      "text": "A beat after 5's screen, 4 sets a down screen for 2. 2 curls off the screen and clears to the weak-side corner, removing 2's defender from any help position near the high post.",
      "detail": "Timing is critical — 4 must not screen too early. The sequential screen removes help defenders from the lane.",
      "actions": [
        {
          "type": "screen",
          "screener": "4",
          "cutter": "2",
          "at": "right_elbow",
          "cutter_to": "right_corner"
        }
      ]
    },
    {
      "label": "Phase 3",
      "text": "4 seals their defender and holds at the high post after screening. 1 dribbles across the top to improve the passing angle, then passes to 4 at the high post for a 1-on-1 isolation.",
      "detail": "4 must establish contact and seal immediately. 1's extra dribbles create a cleaner passing lane before delivering the ball.",
      "actions": [
        {
          "type": "dribble",
          "player": "1",
          "to": "right_slot",
          "bias": "right"
        },
        {
          "type": "cut",
          "player": "4",
          "to": "high_post"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "4"
        }
      ]
    }
  ]
} as const;

export const playBoxLoopPost: Play = {
  "name": "Box Loop Post",
  "tag": "SLOB",
  "desc": "A SLOB play from a box set using sequential down screens to isolate the best post player (4) at the high post for a 1-on-1 opportunity. 5 screens for 1 to get the ball in, then 4 screens for 2 to clear help defenders, before sealing at the high post for a pass from 1.",
  "players": {
    "1": [
      -8,
      19
    ],
    "2": [
      8,
      19
    ],
    "3": [
      -26,
      25
    ],
    "4": [
      8,
      5
    ],
    "5": [
      -8,
      5
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Wing 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "3",
  "phases": [
    {
      "label": "Phase 1",
      "text": "5 sets a down screen for 1, who cuts to the top of the key. 3 inbounds the ball to 1. 5 holds below the block after screening. 3 steps onto the court.",
      "detail": "The down screen by 5 frees 1 at the top of the key to receive the inbound pass cleanly.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 5 C -5.71 7.73, -5.71 12.4, -8 19",
          "move": {
            "id": "5",
            "to": [
              -8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 19 C -7.67 24.77, -5.01 29.11, 0 32",
          "move": {
            "id": "1",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -26 25 L 0 32",
          "dashed": true,
          "ball": {
            "from": "3",
            "to": "1"
          }
        }
      ]
    },
    {
      "label": "Phase 2",
      "text": "A beat after 5's screen, 4 sets a down screen for 2. 2 curls off the screen and clears to the weak-side corner, removing 2's defender from any help position near the high post.",
      "detail": "Timing is critical — 4 must not screen too early. The sequential screen removes help defenders from the lane.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 8 5 C 5.71 7.73, 5.71 12.4, 8 19",
          "move": {
            "id": "4",
            "to": [
              8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 19 C 16.03 16.88, 21.37 11.88, 24 4",
          "move": {
            "id": "2",
            "to": [
              24,
              4
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3",
      "text": "4 seals their defender and holds at the high post after screening. 1 dribbles across the top to improve the passing angle, then passes to 4 at the high post for a 1-on-1 isolation.",
      "detail": "4 must establish contact and seal immediately. 1's extra dribbles create a cleaner passing lane before delivering the ball.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 C 5.05 33.01, 9.39 31.67, 13 28",
          "move": {
            "id": "1",
            "to": [
              13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 19 C 6.05 16.23, 3.39 14.89, 0 15",
          "move": {
            "id": "4",
            "to": [
              0,
              15
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 13 28 L 0 15",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "4"
          }
        }
      ]
    }
  ]
};
