// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "play-piston-elevator"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const playPistonElevatorSemantic = {
  "name": "Piston Elevator",
  "tag": "offense",
  "desc": "A 1-4 high half-court play that disguises itself as an Iverson wing exchange but uses both post players to set an elevator screen, freeing the best shooter for a top-of-key catch-and-shoot three-pointer. The decoy Iverson cut by 3 draws defensive attention while 2 sneaks through the elevator.",
  "players": {
    "1": "top_of_key",
    "2": "right_wing",
    "3": "left_wing",
    "4": "left_elbow",
    "5": "right_elbow"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Center 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1",
      "text": "Decoy Iverson Cut & Baseline Cut. 1 dribbles toward the left wing. 3 makes an Iverson cut off the elbow screens set by 4 and 5 — this is the decoy to draw defensive attention. Simultaneously, 2 makes a baseline cut toward the middle of the key, waiting a beat to allow the elevator screen to be set in time.",
      "detail": "1 must dribble away from 2 (the better shooter). 3 curls over the top of the elbow screens. 2 delays slightly before starting the baseline cut.",
      "actions": [
        {
          "type": "dribble",
          "player": "1",
          "to": "left_wing",
          "bias": "left"
        },
        {
          "type": "cut",
          "player": "3",
          "to": "right_wing",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "2",
          "to": "low_post",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 2",
      "text": "Elevator Screen. After setting the Iverson elbow screens for 3, 4 and 5 quickly pivot and form a side-by-side elevator screen. 2 bursts through the screens to the top of the key and receives the pass from 1 for the catch-and-shoot three-pointer. 4 and 5 close the gate after 2 clears through to seal x2 out.",
      "detail": "4 and 5 close the gate immediately after 2 cuts through. 1 delivers the pass on time for a rhythm catch-and-shoot.",
      "actions": [
        {
          "type": "screen",
          "screener": "4",
          "cutter": "2",
          "at": "high_post",
          "cutter_to": "top_arc",
          "bias": "away_from_basket"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "2"
        }
      ]
    },
    {
      "label": "Phase 3",
      "text": "Counter — Dive to Rim. If x4 anticipates the pass and cuts off the passing lane to 2, 4 dives hard to the hoop for the layup.",
      "detail": "4 reads the defender's overplay on the pass to 2 and immediately dives to the rim. 1 delivers the pass to 4 for the finish.",
      "actions": [
        {
          "type": "cut",
          "player": "4",
          "to": "right_block",
          "bias": "toward_basket"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "4"
        }
      ]
    }
  ]
} as const;

export const playPistonElevator: Play = {
  "name": "Piston Elevator",
  "tag": "offense",
  "desc": "A 1-4 high half-court play that disguises itself as an Iverson wing exchange but uses both post players to set an elevator screen, freeing the best shooter for a top-of-key catch-and-shoot three-pointer. The decoy Iverson cut by 3 draws defensive attention while 2 sneaks through the elevator.",
  "players": {
    "1": [
      0,
      32
    ],
    "2": [
      15,
      22
    ],
    "3": [
      -15,
      22
    ],
    "4": [
      -8,
      19
    ],
    "5": [
      8,
      19
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Center 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1",
      "text": "Decoy Iverson Cut & Baseline Cut. 1 dribbles toward the left wing. 3 makes an Iverson cut off the elbow screens set by 4 and 5 — this is the decoy to draw defensive attention. Simultaneously, 2 makes a baseline cut toward the middle of the key, waiting a beat to allow the elevator screen to be set in time.",
      "detail": "1 must dribble away from 2 (the better shooter). 3 curls over the top of the elbow screens. 2 delays slightly before starting the baseline cut.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 C -6.8 31.37, -11.8 28.03, -15 22",
          "move": {
            "id": "1",
            "to": [
              -15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -15 22 C -5 19, 5 19, 15 22",
          "move": {
            "id": "3",
            "to": [
              15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 15 22 C 8.05 14.39, 3.05 9.06, 0 6",
          "move": {
            "id": "2",
            "to": [
              0,
              6
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2",
      "text": "Elevator Screen. After setting the Iverson elbow screens for 3, 4 and 5 quickly pivot and form a side-by-side elevator screen. 2 bursts through the screens to the top of the key and receives the pass from 1 for the catch-and-shoot three-pointer. 4 and 5 close the gate after 2 clears through to seal x2 out.",
      "detail": "4 and 5 close the gate immediately after 2 cuts through. 1 delivers the pass on time for a rhythm catch-and-shoot.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 19 C -4.61 15.55, -1.95 14.22, 0 15",
          "move": {
            "id": "4",
            "to": [
              0,
              15
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 6 C 0 15, 0 21, 0 24",
          "move": {
            "id": "2",
            "to": [
              0,
              24
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -15 22 L 0 24",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "2"
          }
        }
      ]
    },
    {
      "label": "Phase 3",
      "text": "Counter — Dive to Rim. If x4 anticipates the pass and cuts off the passing lane to 2, 4 dives hard to the hoop for the layup.",
      "detail": "4 reads the defender's overplay on the pass to 2 and immediately dives to the rim. 1 delivers the pass to 4 for the finish.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 15 C 0.73 9.37, 3.4 6.04, 8 5",
          "move": {
            "id": "4",
            "to": [
              8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -15 22 L 8 5",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "4"
          }
        }
      ]
    }
  ]
};
