// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "play-swinger"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const playSwingerSemantic = {
  "name": "Swinger",
  "tag": "PnR",
  "desc": "A man-to-man set play in a 1-3-1 formation that creates a blindside pick-and-roll for the point guard at the top of the key. After shifting the defense with a wing pass, the point guard receives a sudden screen from the high post and attacks the rim with three read-based scoring options: a pull-up, a corner three, or a baseline layup.",
  "players": {
    "1": "top_of_key",
    "2": "left_wing",
    "3": "right_wing",
    "4": "left_block",
    "5": "high_post"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Wing 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Defense Shift",
      "text": "1 passes to 2 on the left wing to shift the defense. 2 immediately passes back to 1 at the top of the key. As the return pass is made, 5 sets a blindside screen on 1's defender at the top of the key — D1 has their back turned after chasing the initial pass.",
      "detail": "The two-pass sequence (1→2→1) pulls D1 off-balance and sets up the blindside screen perfectly.",
      "actions": [
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "2"
        },
        {
          "type": "pass",
          "from_player": "2",
          "to_player": "1"
        },
        {
          "type": "screen",
          "screener": "5",
          "cutter": "1",
          "at": "ball_screen_top",
          "cutter_to": "top_of_key"
        }
      ]
    },
    {
      "label": "Phase 2 — Pick-and-Roll Attack",
      "text": "1 immediately uses 5's blindside screen and attacks toward the rim. Simultaneously, 3 slides down to the right corner and 4 slides along the baseline to find a hole in the defense. 5 rolls toward the basket after setting the screen.",
      "detail": "All three off-ball players relocate to create three distinct passing windows for 1 off the drive.",
      "actions": [
        {
          "type": "dribble",
          "player": "1",
          "to": "high_post",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "3",
          "to": "right_corner"
        },
        {
          "type": "cut",
          "player": "5",
          "to": "low_post",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 3 — Read and Score",
      "text": "1 reads the defense off the drive and selects one of three options: (1) No help — 1 pulls up for a jump shot. (2) D4 steps out — 1 passes to 3 in the right corner for a three-point shot. (3) D5 steps out — 1 bounce passes to 4 sliding along the baseline for a layup.",
      "detail": "Option 2 targets the corner three when help comes from 3's defender. Option 3 targets the baseline when 5's roll is defended.",
      "actions": [
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "3"
        },
        {
          "type": "cut",
          "player": "4",
          "to": "left_short_corner",
          "bias": "toward_basket"
        }
      ]
    }
  ]
} as const;

export const playSwinger: Play = {
  "name": "Swinger",
  "tag": "PnR",
  "desc": "A man-to-man set play in a 1-3-1 formation that creates a blindside pick-and-roll for the point guard at the top of the key. After shifting the defense with a wing pass, the point guard receives a sudden screen from the high post and attacks the rim with three read-based scoring options: a pull-up, a corner three, or a baseline layup.",
  "players": {
    "1": [
      0,
      32
    ],
    "2": [
      -15,
      22
    ],
    "3": [
      15,
      22
    ],
    "4": [
      -8,
      5
    ],
    "5": [
      0,
      15
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Wing 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Defense Shift",
      "text": "1 passes to 2 on the left wing to shift the defense. 2 immediately passes back to 1 at the top of the key. As the return pass is made, 5 sets a blindside screen on 1's defender at the top of the key — D1 has their back turned after chasing the initial pass.",
      "detail": "The two-pass sequence (1→2→1) pulls D1 off-balance and sets up the blindside screen perfectly.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 L -15 22",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "2"
          }
        },
        {
          "marker": "arrow",
          "path": "M -15 22 L 0 32",
          "dashed": true,
          "ball": {
            "from": "2",
            "to": "1"
          }
        },
        {
          "marker": "screen",
          "path": "M 0 15 C 0 15.58, 0 17.92, 0 22",
          "move": {
            "id": "5",
            "to": [
              0,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 32 C 0 32, 0 32, 0 32",
          "move": {
            "id": "1",
            "to": [
              0,
              32
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2 — Pick-and-Roll Attack",
      "text": "1 immediately uses 5's blindside screen and attacks toward the rim. Simultaneously, 3 slides down to the right corner and 4 slides along the baseline to find a hole in the defense. 5 rolls toward the basket after setting the screen.",
      "detail": "All three off-ball players relocate to create three distinct passing windows for 1 off the drive.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 C 0 23.33, 0 17.67, 0 15",
          "move": {
            "id": "1",
            "to": [
              0,
              15
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 15 22 C 21.24 17.62, 24.24 11.62, 24 4",
          "move": {
            "id": "3",
            "to": [
              24,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 22 C 0 13.67, 0 8.33, 0 6",
          "move": {
            "id": "5",
            "to": [
              0,
              6
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3 — Read and Score",
      "text": "1 reads the defense off the drive and selects one of three options: (1) No help — 1 pulls up for a jump shot. (2) D4 steps out — 1 passes to 3 in the right corner for a three-point shot. (3) D5 steps out — 1 bounce passes to 4 sliding along the baseline for a layup.",
      "detail": "Option 2 targets the corner three when help comes from 3's defender. Option 3 targets the baseline when 5's roll is defended.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 15 L 24 4",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "3"
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 5 C -8.66 4.79, -11.32 4.46, -16 4",
          "move": {
            "id": "4",
            "to": [
              -16,
              4
            ]
          }
        }
      ]
    }
  ]
};
