// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "play-inside-isolate"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const playInsideIsolateSemantic = {
  "name": "Inside Isolate",
  "tag": "POST-ISO",
  "desc": "A half-court 4-out 1-in set that isolates the best post mismatch on the low block. Perimeter wing-to-slot screen exchanges keep defenders occupied and prevent help defense from collapsing on the post player.",
  "players": {
    "1": "top_of_key",
    "2": "left_slot",
    "3": "right_wing",
    "4": "left_wing",
    "5": "high_post"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Wing 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1: Wing Entry & Flash",
      "text": "1 passes to 3 on the right wing. Simultaneously, 5 flashes from the high post down to the right block to establish a low-post position on the ball side.",
      "detail": "The pass triggers 5's flash toward the ball-side low post to exploit the mismatch. 5 should seal the defender and call for the ball.",
      "actions": [
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "3"
        },
        {
          "type": "cut",
          "player": "5",
          "to": "right_block",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 2: Post Feed & Perimeter Screen Exchange",
      "text": "3 feeds 5 on the right low block. Simultaneously, 4 screens up for 2 on the left side, and they exchange positions — 2 cuts to the left wing while 4 moves to the left slot. This constant perimeter movement prevents defenders from sagging to help on 5.",
      "detail": "The wing-to-slot screen exchange must be active and purposeful. The entry pass must come from the wing (3), not the slot, to minimize steal/deflection risk.",
      "actions": [
        {
          "type": "pass",
          "from_player": "3",
          "to_player": "5"
        },
        {
          "type": "screen",
          "screener": "4",
          "cutter": "2",
          "at": "left_45",
          "cutter_to": "left_wing"
        }
      ]
    },
    {
      "label": "Phase 3: Post Isolation",
      "text": "5 works 1-on-1 on the right low block. Options include backing down the defender for a power move, facing up and attacking the middle, or facing up and attacking the baseline. If doubled, 5 kicks out to the open perimeter player.",
      "detail": "Perimeter players (1, 2, 4) remain active above the free-throw line to occupy defenders and be ready as kick-out targets if the defense doubles.",
      "actions": [
        {
          "type": "dribble",
          "player": "5",
          "to": "right_block",
          "bias": "toward_basket"
        }
      ]
    }
  ]
} as const;

export const playInsideIsolate: Play = {
  "name": "Inside Isolate",
  "tag": "POST-ISO",
  "desc": "A half-court 4-out 1-in set that isolates the best post mismatch on the low block. Perimeter wing-to-slot screen exchanges keep defenders occupied and prevent help defense from collapsing on the post player.",
  "players": {
    "1": [
      0,
      32
    ],
    "2": [
      -13,
      28
    ],
    "3": [
      15,
      22
    ],
    "4": [
      -15,
      22
    ],
    "5": [
      0,
      15
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Wing 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1: Wing Entry & Flash",
      "text": "1 passes to 3 on the right wing. Simultaneously, 5 flashes from the high post down to the right block to establish a low-post position on the ball side.",
      "detail": "The pass triggers 5's flash toward the ball-side low post to exploit the mismatch. 5 should seal the defender and call for the ball.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 L 15 22",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "3"
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 15 C 0.73 9.37, 3.4 6.04, 8 5",
          "move": {
            "id": "5",
            "to": [
              8,
              5
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2: Post Feed & Perimeter Screen Exchange",
      "text": "3 feeds 5 on the right low block. Simultaneously, 4 screens up for 2 on the left side, and they exchange positions — 2 cuts to the left wing while 4 moves to the left slot. This constant perimeter movement prevents defenders from sagging to help on 5.",
      "detail": "The wing-to-slot screen exchange must be active and purposeful. The entry pass must come from the wing (3), not the slot, to minimize steal/deflection risk.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 15 22 L 8 5",
          "dashed": true,
          "ball": {
            "from": "3",
            "to": "5"
          }
        },
        {
          "marker": "screen",
          "path": "M -15 22 C -14.31 18.03, -15.31 15.36, -18 14",
          "move": {
            "id": "4",
            "to": [
              -18,
              14
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -13 28 C -12.59 25.64, -13.25 23.64, -15 22",
          "move": {
            "id": "2",
            "to": [
              -15,
              22
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3: Post Isolation",
      "text": "5 works 1-on-1 on the right low block. Options include backing down the defender for a power move, facing up and attacking the middle, or facing up and attacking the baseline. If doubled, 5 kicks out to the open perimeter player.",
      "detail": "Perimeter players (1, 2, 4) remain active above the free-throw line to occupy defenders and be ready as kick-out targets if the defense doubles.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 8 5 C 8 5, 8 5, 8 5",
          "move": {
            "id": "5",
            "to": [
              8,
              5
            ]
          }
        }
      ]
    }
  ]
};
