// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "play-double-curls"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const playDoubleCurlsSemantic = {
  "name": "High-Post Double Curls",
  "tag": "offense",
  "desc": "A 1-4 high half-court play that sequences two curl-to-rim cuts (a High-Post cut and a staggered-screen curl) before flowing into a wing pick-and-roll. Both post players screen first, keeping them out of the paint during the PnR phase and leaving only the defensive point guard in the lane.",
  "players": {
    "1": "top_of_key",
    "2": "left_wing",
    "3": "right_wing",
    "4": "left_elbow",
    "5": "right_elbow"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Wing Entry & High-Post Cut",
      "text": "1 passes to 3 on the right wing. 1 immediately cuts off 5's screen at the high post toward the rim, looking to receive the pass from 3 for a layup. If not open, 1 clears to the weak-side corner.",
      "detail": "5 sets a screen at the high post (right elbow area) for 1. 3 looks to hit 1 at the rim; if unavailable, 1 clears weak-side.",
      "actions": [
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "3"
        },
        {
          "type": "screen",
          "screener": "5",
          "cutter": "1",
          "at": "high_post",
          "cutter_to": "left_block",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 2 — Staggered Screen: Second Curl",
      "text": "4 and 5 set a staggered screen for 2, who curls toward the rim looking for the pass from 3. If 2 is not open, 2 clears to the ball-side corner. 4 pops out to the top of the key after screening.",
      "detail": "Staggered screens: 4 screens first near the left elbow, then 5 screens near the high post. 2 uses both screens to curl toward the rim.",
      "actions": [
        {
          "type": "screen",
          "screener": "4",
          "cutter": "2",
          "at": "left_slot",
          "cutter_to": "right_block",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "4",
          "to": "top_of_key",
          "bias": "away_from_basket"
        }
      ]
    },
    {
      "label": "Phase 3 — Wing Pick-and-Roll",
      "text": "5 sets a pick-and-roll for 3 on the right wing. 3 attacks the rim hard looking to score or create a play for a teammate. With 4 and 5 having been used as screeners, only the defensive point guard is left in the lane.",
      "detail": "5 sets the ball screen for 3 at the right wing. 3 attacks; 5 rolls to the rim. Corner players (1, 2) are kick-out options.",
      "actions": [
        {
          "type": "screen",
          "screener": "5",
          "cutter": "3",
          "at": "right_wing",
          "cutter_to": "right_slot",
          "bias": "toward_basket"
        }
      ]
    }
  ]
} as const;

export const playDoubleCurls: Play = {
  "name": "High-Post Double Curls",
  "tag": "offense",
  "desc": "A 1-4 high half-court play that sequences two curl-to-rim cuts (a High-Post cut and a staggered-screen curl) before flowing into a wing pick-and-roll. Both post players screen first, keeping them out of the paint during the PnR phase and leaving only the defensive point guard in the lane.",
  "players": {
    "1": [
      0,
      32
    ],
    "2": [
      -15,
      22
    ],
    "3": [
      15,
      22
    ],
    "4": [
      -8,
      19
    ],
    "5": [
      8,
      19
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Wing Entry & High-Post Cut",
      "text": "1 passes to 3 on the right wing. 1 immediately cuts off 5's screen at the high post toward the rim, looking to receive the pass from 3 for a layup. If not open, 1 clears to the weak-side corner.",
      "detail": "5 sets a screen at the high post (right elbow area) for 1. 3 looks to hit 1 at the rim; if unavailable, 1 clears weak-side.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 L 15 22",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "3"
          }
        },
        {
          "marker": "screen",
          "path": "M 8 19 C 4.61 15.55, 1.95 14.22, 0 15",
          "move": {
            "id": "5",
            "to": [
              0,
              15
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 32 C -1.8 20.13, -4.47 11.13, -8 5",
          "move": {
            "id": "1",
            "to": [
              -8,
              5
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2 — Staggered Screen: Second Curl",
      "text": "4 and 5 set a staggered screen for 2, who curls toward the rim looking for the pass from 3. If 2 is not open, 2 clears to the ball-side corner. 4 pops out to the top of the key after screening.",
      "detail": "Staggered screens: 4 screens first near the left elbow, then 5 screens near the high post. 2 uses both screens to curl toward the rim.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 19 C -8.38 19.77, -10.05 22.77, -13 28",
          "move": {
            "id": "4",
            "to": [
              -13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -15 22 C -6.16 13.57, 1.5 7.9, 8 5",
          "move": {
            "id": "2",
            "to": [
              8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -13 28 C -9.43 32.23, -5.1 33.57, 0 32",
          "move": {
            "id": "4",
            "to": [
              0,
              32
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3 — Wing Pick-and-Roll",
      "text": "5 sets a pick-and-roll for 3 on the right wing. 3 attacks the rim hard looking to score or create a play for a teammate. With 4 and 5 having been used as screeners, only the defensive point guard is left in the lane.",
      "detail": "5 sets the ball screen for 3 at the right wing. 3 attacks; 5 rolls to the rim. Corner players (1, 2) are kick-out options.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 0 15 C 3.52 14.72, 8.52 17.06, 15 22",
          "move": {
            "id": "5",
            "to": [
              15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 15 22 C 13.42 22.71, 12.75 24.71, 13 28",
          "move": {
            "id": "3",
            "to": [
              13,
              28
            ]
          }
        }
      ]
    }
  ]
};
