// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "play-high-post-double-screen"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const playHighPostDoubleScreenSemantic = {
  "name": "High-Post",
  "tag": "half-court",
  "desc": "A 1-4 high man-to-man half-court play. 1 passes to 2 on the wing and makes a High-Post cut off 5's screen for a layup attempt. If not open, 5 steps up to set a PnR for 2, while 3 and 4 set a weak-side double screen freeing 1 for a catch-and-shoot. 2 reads: pass to 1, attack themselves, or hit 5 rolling to the rim.",
  "players": {
    "1": "top_of_key",
    "2": "right_wing",
    "3": "left_wing",
    "4": "left_elbow",
    "5": "right_elbow"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1",
      "text": "1 passes to 2 on the right wing, then immediately makes a High-Post cut off 5's screen, driving toward the basket looking for the return pass and layup.",
      "detail": "2 must look for 1 on the cut before moving on to the PnR action. This is a genuine scoring threat.",
      "actions": [
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "2"
        },
        {
          "type": "screen",
          "screener": "5",
          "cutter": "1",
          "at": "high_post",
          "cutter_to": "low_post",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 2",
      "text": "If 1 is not open on the cut, 5 steps across to set an on-ball PnR screen for 2 at the top of the key. Simultaneously, 3 and 4 walk their defenders down to the weak-side blocks to build the double screen for 1.",
      "detail": "3 and 4 must walk defenders down naturally — do not telegraph the double screen by sprinting early.",
      "actions": [
        {
          "type": "cut",
          "player": "5",
          "to": "ball_screen_top",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "3",
          "to": "left_block",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "4",
          "to": "left_short_corner",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 3",
      "text": "2 uses 5's screen and attacks the middle of the floor. 5 rolls to the rim. Simultaneously, 1 cuts hard off the double screen from 3 and 4, getting open for the catch-and-shoot on the weak side. 2 reads: (a) pass to 1 for the jump shot, (b) attack the rim or pull up mid-range, or (c) pass to 5 rolling to the rim.",
      "detail": "1 should cut to a distance within their shooting range. 5's PnR screen angle must direct 2 toward the rim, not the sideline.",
      "actions": [
        {
          "type": "dribble",
          "player": "2",
          "to": "high_post",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "5",
          "to": "low_post",
          "bias": "toward_basket"
        },
        {
          "type": "screen",
          "screener": "3",
          "cutter": "1",
          "at": "left_block",
          "cutter_to": "left_slot",
          "bias": "away_from_basket"
        }
      ]
    }
  ]
} as const;

export const playHighPostDoubleScreen: Play = {
  "name": "High-Post",
  "tag": "half-court",
  "desc": "A 1-4 high man-to-man half-court play. 1 passes to 2 on the wing and makes a High-Post cut off 5's screen for a layup attempt. If not open, 5 steps up to set a PnR for 2, while 3 and 4 set a weak-side double screen freeing 1 for a catch-and-shoot. 2 reads: pass to 1, attack themselves, or hit 5 rolling to the rim.",
  "players": {
    "1": [
      0,
      32
    ],
    "2": [
      15,
      22
    ],
    "3": [
      -15,
      22
    ],
    "4": [
      -8,
      19
    ],
    "5": [
      8,
      19
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1",
      "text": "1 passes to 2 on the right wing, then immediately makes a High-Post cut off 5's screen, driving toward the basket looking for the return pass and layup.",
      "detail": "2 must look for 1 on the cut before moving on to the PnR action. This is a genuine scoring threat.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 L 15 22",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "2"
          }
        },
        {
          "marker": "screen",
          "path": "M 8 19 C 4.61 15.55, 1.95 14.22, 0 15",
          "move": {
            "id": "5",
            "to": [
              0,
              15
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 32 C 0 20.33, 0 11.67, 0 6",
          "move": {
            "id": "1",
            "to": [
              0,
              6
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2",
      "text": "If 1 is not open on the cut, 5 steps across to set an on-ball PnR screen for 2 at the top of the key. Simultaneously, 3 and 4 walk their defenders down to the weak-side blocks to build the double screen for 1.",
      "detail": "3 and 4 must walk defenders down naturally — do not telegraph the double screen by sprinting early.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 15 C 0 15.58, 0 17.92, 0 22",
          "move": {
            "id": "5",
            "to": [
              0,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -15 22 C -10.23 14.58, -7.9 8.92, -8 5",
          "move": {
            "id": "3",
            "to": [
              -8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 19 C -8.01 12.61, -10.67 7.61, -16 4",
          "move": {
            "id": "4",
            "to": [
              -16,
              4
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3",
      "text": "2 uses 5's screen and attacks the middle of the floor. 5 rolls to the rim. Simultaneously, 1 cuts hard off the double screen from 3 and 4, getting open for the catch-and-shoot on the weak side. 2 reads: (a) pass to 1 for the jump shot, (b) attack the rim or pull up mid-range, or (c) pass to 5 rolling to the rim.",
      "detail": "1 should cut to a distance within their shooting range. 5's PnR screen angle must direct 2 toward the rim, not the sideline.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 15 22 C 8.52 17.06, 3.52 14.72, 0 15",
          "move": {
            "id": "2",
            "to": [
              0,
              15
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 22 C 0 13.67, 0 8.33, 0 6",
          "move": {
            "id": "5",
            "to": [
              0,
              6
            ]
          }
        },
        {
          "marker": "screen",
          "path": "M -8 5 C -8 5, -8 5, -8 5",
          "move": {
            "id": "3",
            "to": [
              -8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 6 C -5.79 15.96, -10.12 23.29, -13 28",
          "move": {
            "id": "1",
            "to": [
              -13,
              28
            ]
          }
        }
      ]
    }
  ]
};
