// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "play-black"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const playBlackSemantic = {
  "name": "Black",
  "tag": "offense",
  "desc": "A quick man-to-man play from a 5-out formation. A step-up screen from the corner frees the wing for an immediate baseline drive. The opposite post flashes into the key to counter the defensive rotation, creating a layup opportunity or a kick-out to a perimeter player.",
  "players": {
    "1": "top_of_key",
    "2": "left_wing",
    "3": "right_wing",
    "4": "left_corner",
    "5": "right_corner"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Wing 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Wing Entry & Step-Up Screen",
      "text": "1 passes to 2 on the left wing. Simultaneously, 4 steps up from the left corner to set a strong screen on 2's defender.",
      "detail": "4 must set the screen immediately as the ball is in the air so 2 can attack off the catch before D2 recovers.",
      "actions": [
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "2"
        },
        {
          "type": "screen",
          "screener": "4",
          "cutter": "2",
          "at": "left_slot",
          "cutter_to": "left_block"
        }
      ]
    },
    {
      "label": "Phase 2 — Baseline Drive",
      "text": "2 receives the pass and immediately rips through, attacking baseline toward the rim on the catch. 5 flashes from the right corner up to the left elbow area to counter the defensive rotation.",
      "detail": "2 must attack on the catch — any delay allows D2 to recover off the screen. 5's flash exploits the help defender who has rotated toward the drive.",
      "actions": [
        {
          "type": "dribble",
          "player": "2",
          "to": "baseline_center",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "5",
          "to": "left_elbow",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 3 — Finish, Drop Pass, or Kick-Out",
      "text": "2 chooses from three options: (A) finish the baseline drive at the basket; (B) drop pass to 5 at the elbow/mid-lane for the score inside; (C) if the defense rotates down to stop 5, kick out to 3 on the right wing for an open perimeter shot.",
      "detail": "The primary read is 2's own drive. If help collapses, 5 is the second read. If 5's man also rotates, 3 is left alone on the perimeter.",
      "actions": [
        {
          "type": "pass",
          "from_player": "2",
          "to_player": "5"
        },
        {
          "type": "cut",
          "player": "3",
          "to": "right_wing",
          "bias": "away_from_basket"
        }
      ]
    }
  ]
} as const;

export const playBlack: Play = {
  "name": "Black",
  "tag": "offense",
  "desc": "A quick man-to-man play from a 5-out formation. A step-up screen from the corner frees the wing for an immediate baseline drive. The opposite post flashes into the key to counter the defensive rotation, creating a layup opportunity or a kick-out to a perimeter player.",
  "players": {
    "1": [
      0,
      32
    ],
    "2": [
      -15,
      22
    ],
    "3": [
      15,
      22
    ],
    "4": [
      -24,
      4
    ],
    "5": [
      24,
      4
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Wing 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Post 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 — Wing Entry & Step-Up Screen",
      "text": "1 passes to 2 on the left wing. Simultaneously, 4 steps up from the left corner to set a strong screen on 2's defender.",
      "detail": "4 must set the screen immediately as the ball is in the air so 2 can attack off the catch before D2 recovers.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 L -15 22",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "2"
          }
        },
        {
          "marker": "screen",
          "path": "M -24 4 C -17.74 10.49, -14.07 18.49, -13 28",
          "move": {
            "id": "4",
            "to": [
              -13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -15 22 C -9.61 17.59, -7.27 11.93, -8 5",
          "move": {
            "id": "2",
            "to": [
              -8,
              5
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2 — Baseline Drive",
      "text": "2 receives the pass and immediately rips through, attacking baseline toward the rim on the catch. 5 flashes from the right corner up to the left elbow area to counter the defensive rotation.",
      "detail": "2 must attack on the catch — any delay allows D2 to recover off the screen. 5's flash exploits the help defender who has rotated toward the drive.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M -8 5 C -3.38 4.76, -0.72 3.43, 0 1",
          "move": {
            "id": "2",
            "to": [
              0,
              1
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 24 4 C 10.97 7.15, 0.3 12.15, -8 19",
          "move": {
            "id": "5",
            "to": [
              -8,
              19
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3 — Finish, Drop Pass, or Kick-Out",
      "text": "2 chooses from three options: (A) finish the baseline drive at the basket; (B) drop pass to 5 at the elbow/mid-lane for the score inside; (C) if the defense rotates down to stop 5, kick out to 3 on the right wing for an open perimeter shot.",
      "detail": "The primary read is 2's own drive. If help collapses, 5 is the second read. If 5's man also rotates, 3 is left alone on the perimeter.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 1 L -8 19",
          "dashed": true,
          "ball": {
            "from": "2",
            "to": "5"
          }
        },
        {
          "marker": "arrow",
          "path": "M 15 22 C 15 22, 15 22, 15 22",
          "move": {
            "id": "3",
            "to": [
              15,
              22
            ]
          }
        }
      ]
    }
  ]
};
