// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "play-reverse-dribble-options"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const playReverseDribbleOptionsSemantic = {
  "name": "Continuity — Reverse Dribble Options",
  "tag": "continuity",
  "desc": "When all passing lanes are denied, the Continuity offense shifts into three reverse dribble entries (plus a Double Screen High variant). Each reverse dribble triggers specific cuts, screens, and handoffs to keep the offense flowing.",
  "players": {
    "1": "top_of_key",
    "2": "right_wing",
    "3": "left_wing",
    "4": "right_elbow",
    "5": "top_arc"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Option 1 – Phase 1: Reverse Dribble Triggers",
      "text": "1 cannot pass to any teammate. 1 dribbles toward 2; 2 cuts away to the opposite (left) corner. 1 reverse dribbles back toward 4; 4 goes backdoor toward the rim. 5 flashes to the weak-side elbow.",
      "detail": "Diagram 7.37 ground truth: 1 at top of key, 2 at right wing, 3 at left wing, 4 at right elbow, 5 near top arc.",
      "actions": [
        {
          "type": "dribble",
          "player": "1",
          "to": "right_slot",
          "bias": "right"
        },
        {
          "type": "cut",
          "player": "2",
          "to": "left_corner",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "4",
          "to": "low_post",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "5",
          "to": "left_elbow"
        }
      ]
    },
    {
      "label": "Option 1 – Phase 2: Pass, Side Screen & Down Screen",
      "text": "1 reverse dribbles and passes to 2 (who has relocated). 5 sets a side screen for 1; 1 receives the ball back from 2 for a jump shot or drive. Alternatively, 2 passes to 5 rolling to the basket. 2 can also screen down for 4; 4 receives from 1.",
      "detail": "Diagram 7.38: 1 near top of key, 2 at right wing, 5 at high post/free-throw area, 4 at right elbow, 3 at left wing.",
      "actions": [
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "2"
        },
        {
          "type": "screen",
          "screener": "5",
          "cutter": "1",
          "at": "high_post",
          "cutter_to": "right_slot"
        },
        {
          "type": "screen",
          "screener": "2",
          "cutter": "4",
          "at": "right_elbow",
          "cutter_to": "right_wing"
        }
      ]
    },
    {
      "label": "Option 2 – Phase 1: Guard Reverse Dribble with Down Screens",
      "text": "2 dribbles toward 1, reverse dribbles, then passes to 3. 3 passes to 5 who has flashed outside the lane. 4 screens for 2 cutting back; 3 screens for 1 cutting back to the original side. 5 reads: 2 or 1 off screens, or 4/3 rolling.",
      "detail": "Diagram 7.39: 1 at right guard area, 2 near center initiating reverse dribble, 3 at left wing, 4 at right wing, 5 near top arc/elbow.",
      "actions": [
        {
          "type": "pass",
          "from_player": "2",
          "to_player": "3"
        },
        {
          "type": "pass",
          "from_player": "3",
          "to_player": "5"
        },
        {
          "type": "screen",
          "screener": "4",
          "cutter": "2",
          "at": "right_wing",
          "cutter_to": "right_corner"
        },
        {
          "type": "screen",
          "screener": "3",
          "cutter": "1",
          "at": "left_slot",
          "cutter_to": "left_corner"
        }
      ]
    },
    {
      "label": "Option 2 – Phase 2 Continuity: Ball Reversal & Re-Entry",
      "text": "5 passes to 1 and moves to the low post. 4 pops outside the arc. 1 passes to 2. 2 reverse dribbles; 1 cuts through the lane off 3's screen. 2 passes to 1 or to 3 rolling. 5 side-screens for 2 then pops; 3 passes to 1, 2, 5, or 4 spotting up.",
      "detail": "Diagrams 7.40–7.42 continuity sequence.",
      "actions": [
        {
          "type": "pass",
          "from_player": "5",
          "to_player": "1"
        },
        {
          "type": "cut",
          "player": "5",
          "to": "low_post"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "2"
        },
        {
          "type": "screen",
          "screener": "3",
          "cutter": "1",
          "at": "left_elbow",
          "cutter_to": "right_slot"
        }
      ]
    },
    {
      "label": "Option 3 – Phase 1: 2 Overplayed — Backdoor + Strong-Side Options",
      "text": "2 is overplayed. 1 dribbles toward 2; 2 cuts backdoor to the opposite corner. 1 reverse dribbles. Strong-side options: (a) 4 screens for 2 and rolls to the basket; (b) 4 fakes the screen and cuts to the basket; (c) 4 posts up. 1 passes to 2 or 4.",
      "detail": "Diagrams 7.43–7.44: 1 near top of key, 2 cuts backdoor, 4 at right wing setting/faking screen.",
      "actions": [
        {
          "type": "dribble",
          "player": "1",
          "to": "right_slot",
          "bias": "right"
        },
        {
          "type": "cut",
          "player": "2",
          "to": "left_corner",
          "bias": "toward_basket"
        },
        {
          "type": "screen",
          "screener": "4",
          "cutter": "2",
          "at": "right_wing",
          "cutter_to": "right_corner"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "4"
        }
      ]
    },
    {
      "label": "Option 3 – Phase 2: Pick-and-Roll Continuity",
      "text": "1 passes to 2. 5 sets a screen for 1; 1 gets the ball back from 2 and plays pick-and-roll with 5, who rolls to the basket.",
      "detail": "Diagram shows 5 screening for 1 after 1's pass to 2, then 1 and 5 executing pick-and-roll.",
      "actions": [
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "2"
        },
        {
          "type": "screen",
          "screener": "5",
          "cutter": "1",
          "at": "ball_screen_top",
          "cutter_to": "top_of_key"
        },
        {
          "type": "pass",
          "from_player": "2",
          "to_player": "1"
        }
      ]
    }
  ]
} as const;

export const playReverseDribbleOptions: Play = {
  "name": "Continuity — Reverse Dribble Options",
  "tag": "continuity",
  "desc": "When all passing lanes are denied, the Continuity offense shifts into three reverse dribble entries (plus a Double Screen High variant). Each reverse dribble triggers specific cuts, screens, and handoffs to keep the offense flowing.",
  "players": {
    "1": [
      0,
      32
    ],
    "2": [
      15,
      22
    ],
    "3": [
      -15,
      22
    ],
    "4": [
      8,
      19
    ],
    "5": [
      0,
      24
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Option 1 – Phase 1: Reverse Dribble Triggers",
      "text": "1 cannot pass to any teammate. 1 dribbles toward 2; 2 cuts away to the opposite (left) corner. 1 reverse dribbles back toward 4; 4 goes backdoor toward the rim. 5 flashes to the weak-side elbow.",
      "detail": "Diagram 7.37 ground truth: 1 at top of key, 2 at right wing, 3 at left wing, 4 at right elbow, 5 near top arc.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 C 5.05 33.01, 9.39 31.67, 13 28",
          "move": {
            "id": "1",
            "to": [
              13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 15 22 C 3.51 13.41, -9.49 7.41, -24 4",
          "move": {
            "id": "2",
            "to": [
              -24,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 19 C 3.88 12.04, 1.22 7.71, 0 6",
          "move": {
            "id": "4",
            "to": [
              0,
              6
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 24 C -1.77 20.89, -4.43 19.23, -8 19",
          "move": {
            "id": "5",
            "to": [
              -8,
              19
            ]
          }
        }
      ]
    },
    {
      "label": "Option 1 – Phase 2: Pass, Side Screen & Down Screen",
      "text": "1 reverse dribbles and passes to 2 (who has relocated). 5 sets a side screen for 1; 1 receives the ball back from 2 for a jump shot or drive. Alternatively, 2 passes to 5 rolling to the basket. 2 can also screen down for 4; 4 receives from 1.",
      "detail": "Diagram 7.38: 1 near top of key, 2 at right wing, 5 at high post/free-throw area, 4 at right elbow, 3 at left wing.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 13 28 L -24 4",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "2"
          }
        },
        {
          "marker": "screen",
          "path": "M -8 19 C -4.61 15.55, -1.95 14.22, 0 15",
          "move": {
            "id": "5",
            "to": [
              0,
              15
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 13 28 C 13 28, 13 28, 13 28",
          "move": {
            "id": "1",
            "to": [
              13,
              28
            ]
          }
        },
        {
          "marker": "screen",
          "path": "M -24 4 C -10.97 7.15, -0.3 12.15, 8 19",
          "move": {
            "id": "2",
            "to": [
              8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 6 C 2.12 14.03, 7.12 19.37, 15 22",
          "move": {
            "id": "4",
            "to": [
              15,
              22
            ]
          }
        }
      ]
    },
    {
      "label": "Option 2 – Phase 1: Guard Reverse Dribble with Down Screens",
      "text": "2 dribbles toward 1, reverse dribbles, then passes to 3. 3 passes to 5 who has flashed outside the lane. 4 screens for 2 cutting back; 3 screens for 1 cutting back to the original side. 5 reads: 2 or 1 off screens, or 4/3 rolling.",
      "detail": "Diagram 7.39: 1 at right guard area, 2 near center initiating reverse dribble, 3 at left wing, 4 at right wing, 5 near top arc/elbow.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 8 19 L -15 22",
          "dashed": true,
          "ball": {
            "from": "2",
            "to": "3"
          }
        },
        {
          "marker": "arrow",
          "path": "M -15 22 L 0 15",
          "dashed": true,
          "ball": {
            "from": "3",
            "to": "5"
          }
        },
        {
          "marker": "screen",
          "path": "M 15 22 C 15 22, 15 22, 15 22",
          "move": {
            "id": "4",
            "to": [
              15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 19 C 16.03 16.88, 21.37 11.88, 24 4",
          "move": {
            "id": "2",
            "to": [
              24,
              4
            ]
          }
        },
        {
          "marker": "screen",
          "path": "M -15 22 C -13.42 22.71, -12.75 24.71, -13 28",
          "move": {
            "id": "3",
            "to": [
              -13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 13 28 C 2.84 16.64, -9.49 8.64, -24 4",
          "move": {
            "id": "1",
            "to": [
              -24,
              4
            ]
          }
        }
      ]
    },
    {
      "label": "Option 2 – Phase 2 Continuity: Ball Reversal & Re-Entry",
      "text": "5 passes to 1 and moves to the low post. 4 pops outside the arc. 1 passes to 2. 2 reverse dribbles; 1 cuts through the lane off 3's screen. 2 passes to 1 or to 3 rolling. 5 side-screens for 2 then pops; 3 passes to 1, 2, 5, or 4 spotting up.",
      "detail": "Diagrams 7.40–7.42 continuity sequence.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 15 L -24 4",
          "dashed": true,
          "ball": {
            "from": "5",
            "to": "1"
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 15 C 0 9.75, 0 6.75, 0 6",
          "move": {
            "id": "5",
            "to": [
              0,
              6
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -24 4 L 24 4",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "2"
          }
        },
        {
          "marker": "screen",
          "path": "M -13 28 C -10.05 22.77, -8.38 19.77, -8 19",
          "move": {
            "id": "3",
            "to": [
              -8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -24 4 C -13.84 15.36, -1.51 23.36, 13 28",
          "move": {
            "id": "1",
            "to": [
              13,
              28
            ]
          }
        }
      ]
    },
    {
      "label": "Option 3 – Phase 1: 2 Overplayed — Backdoor + Strong-Side Options",
      "text": "2 is overplayed. 1 dribbles toward 2; 2 cuts backdoor to the opposite corner. 1 reverse dribbles. Strong-side options: (a) 4 screens for 2 and rolls to the basket; (b) 4 fakes the screen and cuts to the basket; (c) 4 posts up. 1 passes to 2 or 4.",
      "detail": "Diagrams 7.43–7.44: 1 near top of key, 2 cuts backdoor, 4 at right wing setting/faking screen.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 13 28 C 13 28, 13 28, 13 28",
          "move": {
            "id": "1",
            "to": [
              13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 24 4 C 8 7, -8 7, -24 4",
          "move": {
            "id": "2",
            "to": [
              -24,
              4
            ]
          }
        },
        {
          "marker": "screen",
          "path": "M 15 22 C 15 22, 15 22, 15 22",
          "move": {
            "id": "4",
            "to": [
              15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -24 4 L 24 4",
          "move": {
            "id": "2",
            "to": [
              24,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 13 28 L 15 22",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "4"
          }
        }
      ]
    },
    {
      "label": "Option 3 – Phase 2: Pick-and-Roll Continuity",
      "text": "1 passes to 2. 5 sets a screen for 1; 1 gets the ball back from 2 and plays pick-and-roll with 5, who rolls to the basket.",
      "detail": "Diagram shows 5 screening for 1 after 1's pass to 2, then 1 and 5 executing pick-and-roll.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 13 28 L 24 4",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "2"
          }
        },
        {
          "marker": "screen",
          "path": "M 0 6 C 0 8.33, 0 13.67, 0 22",
          "move": {
            "id": "5",
            "to": [
              0,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 13 28 C 7.95 26.99, 3.61 28.33, 0 32",
          "move": {
            "id": "1",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 24 4 L 0 32",
          "dashed": true,
          "ball": {
            "from": "2",
            "to": "1"
          }
        }
      ]
    }
  ]
};
