// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "play-flex-warrior"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const playFlexWarriorSemantic = {
  "name": "Flex Warrior",
  "tag": "offense",
  "desc": "A multi-action half-court play from a horns set featuring a flex screen, a screen-the-screener action, and a post seal. Creates open catch-and-shoot looks for the PG and wing, plus a deep post-up option for the center.",
  "players": {
    "1": "top_of_key",
    "2": "right_wing",
    "3": "left_wing",
    "4": "left_elbow",
    "5": "right_elbow"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1: Flex Screen Action",
      "text": "1 passes to 4 at the left elbow. 1 then cuts down the center of the lane to set a flex screen for 2. 2 cuts off the flex screen toward the rim, looking for the pass from 4 for an easy layup.",
      "actions": [
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "4"
        },
        {
          "type": "screen",
          "screener": "1",
          "cutter": "2",
          "at": "left_block",
          "cutter_to": "low_post",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 2: Screen-the-Screener (STS)",
      "text": "As 2 uses the flex screen, 5 sets a down screen for 1 — a classic screen-the-screener action. 1 uses the down screen and cuts to the right slot, looking for the catch-and-shoot from 4.",
      "actions": [
        {
          "type": "screen",
          "screener": "5",
          "cutter": "1",
          "at": "right_elbow",
          "cutter_to": "right_slot",
          "bias": "away_from_basket"
        }
      ]
    },
    {
      "label": "Phase 3: Second Screen for 2 & Post Seal",
      "text": "5 immediately sets another screen for 2, who cuts out to the right wing. If 1 was not open, 4 swings the ball to 1, who passes to 2 on the wing. After screening, 5 seals deep in the paint for a potential post feed from 2.",
      "actions": [
        {
          "type": "pass",
          "from_player": "4",
          "to_player": "1"
        },
        {
          "type": "screen",
          "screener": "5",
          "cutter": "2",
          "at": "right_short_corner",
          "cutter_to": "right_wing",
          "bias": "away_from_basket"
        }
      ]
    },
    {
      "label": "Phase 4: Wing Pass & Post Feed",
      "text": "1 swings the ball to 2 on the right wing. 5, after screening, seals deep in the paint. If the wing shot is not there, 2 looks to feed 5 on the deep post seal for the score.",
      "actions": [
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "2"
        },
        {
          "type": "cut",
          "player": "5",
          "to": "low_post",
          "bias": "toward_basket"
        }
      ]
    }
  ]
} as const;

export const playFlexWarrior: Play = {
  "name": "Flex Warrior",
  "tag": "offense",
  "desc": "A multi-action half-court play from a horns set featuring a flex screen, a screen-the-screener action, and a post seal. Creates open catch-and-shoot looks for the PG and wing, plus a deep post-up option for the center.",
  "players": {
    "1": [
      0,
      32
    ],
    "2": [
      15,
      22
    ],
    "3": [
      -15,
      22
    ],
    "4": [
      -8,
      19
    ],
    "5": [
      8,
      19
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1: Flex Screen Action",
      "text": "1 passes to 4 at the left elbow. 1 then cuts down the center of the lane to set a flex screen for 2. 2 cuts off the flex screen toward the rim, looking for the pass from 4 for an easy layup.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 L -8 19",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "4"
          }
        },
        {
          "marker": "screen",
          "path": "M 0 32 C -1.8 20.13, -4.47 11.13, -8 5",
          "move": {
            "id": "1",
            "to": [
              -8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 15 22 C 8.05 14.39, 3.05 9.06, 0 6",
          "move": {
            "id": "2",
            "to": [
              0,
              6
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2: Screen-the-Screener (STS)",
      "text": "As 2 uses the flex screen, 5 sets a down screen for 1 — a classic screen-the-screener action. 1 uses the down screen and cuts to the right slot, looking for the catch-and-shoot from 4.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 8 19 C 8 19, 8 19, 8 19",
          "move": {
            "id": "5",
            "to": [
              8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 5 C -0.35 15.6, 6.65 23.26, 13 28",
          "move": {
            "id": "1",
            "to": [
              13,
              28
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3: Second Screen for 2 & Post Seal",
      "text": "5 immediately sets another screen for 2, who cuts out to the right wing. If 1 was not open, 4 swings the ball to 1, who passes to 2 on the wing. After screening, 5 seals deep in the paint for a potential post feed from 2.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M -8 19 L 13 28",
          "dashed": true,
          "ball": {
            "from": "4",
            "to": "1"
          }
        },
        {
          "marker": "screen",
          "path": "M 8 19 C 8.01 12.61, 10.67 7.61, 16 4",
          "move": {
            "id": "5",
            "to": [
              16,
              4
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 6 C 6.95 13.61, 11.95 18.94, 15 22",
          "move": {
            "id": "2",
            "to": [
              15,
              22
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 4: Wing Pass & Post Feed",
      "text": "1 swings the ball to 2 on the right wing. 5, after screening, seals deep in the paint. If the wing shot is not there, 2 looks to feed 5 on the deep post seal for the score.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 13 28 L 15 22",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "2"
          }
        },
        {
          "marker": "arrow",
          "path": "M 16 4 C 7.67 4.76, 2.33 5.43, 0 6",
          "move": {
            "id": "5",
            "to": [
              0,
              6
            ]
          }
        }
      ]
    }
  ]
};
