// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "play-side-blaze"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const playSideBlazeSemantic = {
  "name": "Side Blaze",
  "tag": "offense",
  "desc": "A quick half-court play from a horns set. 1 passes to 4 and cuts opposite. 4 dribbles into a hand-off for 2 on the wing while 1 sets a weak-side down screen for 3. 5 immediately sets an on-ball screen for 2, who attacks the middle with options to finish, hit 4 rolling, or kick to 1.",
  "players": {
    "1": "top_of_key",
    "2": "right_corner",
    "3": "left_corner",
    "4": "right_elbow",
    "5": "left_elbow"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 – Wing Entry",
      "text": "4 steps out from the right elbow toward the wing to receive the entry pass from 1. Simultaneously, 1 cuts to the opposite (left) wing.",
      "detail": "Horns set entry. 4 pops toward the wing to accept the pass; 1 immediately cuts away to create spacing and set up the weak-side action.",
      "actions": [
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "4"
        },
        {
          "type": "cut",
          "player": "1",
          "to": "left_wing",
          "bias": "away_from_basket"
        }
      ]
    },
    {
      "label": "Phase 2 – Dribble Hand-Off & Weak-Side Down Screen",
      "text": "4 dribbles down toward 2 in the right corner. 2 jabs toward the basket then explodes up to the right wing to receive the dribble hand-off. Simultaneously, 1 sets a down screen for 3 on the weak side; 3 uses the screen to exchange up to the left wing while 1 dives to the left corner.",
      "detail": "The weak-side screen exchange occupies help defenders and keeps the paint clear for the upcoming PnR attack.",
      "actions": [
        {
          "type": "handoff",
          "giver": "4",
          "receiver": "2",
          "at": "right_wing"
        },
        {
          "type": "screen",
          "screener": "1",
          "cutter": "3",
          "at": "left_slot",
          "cutter_to": "left_wing",
          "bias": "away_from_basket"
        }
      ]
    },
    {
      "label": "Phase 3 – Pick-and-Roll & Roll Man",
      "text": "5 sprints from the left elbow to set an on-ball screen for 2 at the top of the key area. 4 rolls hard to the rim immediately after the hand-off. 2 attacks the middle off the screen and reads: layup, pass to 4 rolling, or kick-out to 1.",
      "detail": "4 is often wide open on the roll because x4 shifts attention to the hand-off. 2 must stay low and decisive off the screen.",
      "actions": [
        {
          "type": "screen",
          "screener": "5",
          "cutter": "2",
          "at": "ball_screen_top",
          "cutter_to": "high_post",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "4",
          "to": "low_post",
          "bias": "toward_basket"
        }
      ]
    }
  ]
} as const;

export const playSideBlaze: Play = {
  "name": "Side Blaze",
  "tag": "offense",
  "desc": "A quick half-court play from a horns set. 1 passes to 4 and cuts opposite. 4 dribbles into a hand-off for 2 on the wing while 1 sets a weak-side down screen for 3. 5 immediately sets an on-ball screen for 2, who attacks the middle with options to finish, hit 4 rolling, or kick to 1.",
  "players": {
    "1": [
      0,
      32
    ],
    "2": [
      24,
      4
    ],
    "3": [
      -24,
      4
    ],
    "4": [
      8,
      19
    ],
    "5": [
      -8,
      19
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "1",
  "phases": [
    {
      "label": "Phase 1 – Wing Entry",
      "text": "4 steps out from the right elbow toward the wing to receive the entry pass from 1. Simultaneously, 1 cuts to the opposite (left) wing.",
      "detail": "Horns set entry. 4 pops toward the wing to accept the pass; 1 immediately cuts away to create spacing and set up the weak-side action.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 L 8 19",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "4"
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 32 C -5.98 31.5, -10.98 28.17, -15 22",
          "move": {
            "id": "1",
            "to": [
              -15,
              22
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 2 – Dribble Hand-Off & Weak-Side Down Screen",
      "text": "4 dribbles down toward 2 in the right corner. 2 jabs toward the basket then explodes up to the right wing to receive the dribble hand-off. Simultaneously, 1 sets a down screen for 3 on the weak side; 3 uses the screen to exchange up to the left wing while 1 dives to the left corner.",
      "detail": "The weak-side screen exchange occupies help defenders and keeps the paint clear for the upcoming PnR attack.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 8 19 L 15 22",
          "move": {
            "id": "4",
            "to": [
              15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 15 22 L 24 4",
          "dashed": true,
          "ball": {
            "from": "4",
            "to": "2"
          }
        },
        {
          "marker": "screen",
          "path": "M -15 22 C -13.42 22.71, -12.75 24.71, -13 28",
          "move": {
            "id": "1",
            "to": [
              -13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -24 4 C -23.79 11.11, -20.79 17.11, -15 22",
          "move": {
            "id": "3",
            "to": [
              -15,
              22
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3 – Pick-and-Roll & Roll Man",
      "text": "5 sprints from the left elbow to set an on-ball screen for 2 at the top of the key area. 4 rolls hard to the rim immediately after the hand-off. 2 attacks the middle off the screen and reads: layup, pass to 4 rolling, or kick-out to 1.",
      "detail": "4 is often wide open on the roll because x4 shifts attention to the hand-off. 2 must stay low and decisive off the screen.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 19 C -4.79 17.93, -2.12 18.93, 0 22",
          "move": {
            "id": "5",
            "to": [
              0,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 24 4 C 13.17 6.67, 5.17 10.33, 0 15",
          "move": {
            "id": "2",
            "to": [
              0,
              15
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 15 22 C 8.05 14.39, 3.05 9.06, 0 6",
          "move": {
            "id": "4",
            "to": [
              0,
              6
            ]
          }
        }
      ]
    }
  ]
};
