// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "slob-x"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const slobXSemantic = {
  "name": "SLOB X",
  "tag": "SLOB",
  "desc": "A sideline out-of-bounds box-set play that uses two sequential waves of staggered screens to free two different shooters — first 2 on one wing, then 3 on the opposite wing — for open mid-range or three-point shots. 3 inbounds, 1 receives the entry pass at the top, then looks to kick out to whichever shooter comes free.",
  "players": {
    "1": "right_elbow",
    "2": "left_elbow",
    "3": "sideline_left_high",
    "4": "right_block",
    "5": "left_block"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "3",
  "phases": [
    {
      "label": "Phase 1",
      "text": "2 sets a diagonal down-screen for 1, who pops to the top of the key. 3 inbounds to 1 and steps onto the court.",
      "detail": "Entry action. 2 uses the screen as a decoy/setter — their cut to the screen frees 1 to pop to the top. 3 delivers the inbound pass to 1 at the top of the key and immediately enters the court near the left wing area.",
      "actions": [
        {
          "type": "screen",
          "screener": "2",
          "cutter": "1",
          "at": "high_post",
          "cutter_to": "top_of_key"
        },
        {
          "type": "pass",
          "from_player": "3",
          "to_player": "1"
        }
      ]
    },
    {
      "label": "Phase 2",
      "text": "2 cuts off a staggered screen set first by 5 then by 3, curling out to the left wing for the primary shot look. 4 walks down toward the right block to set up the next action.",
      "detail": "Primary read: 1 looks to hit 2 on the left wing off the staggered screens from 5 and 3. 4 repositions to the right short corner to be ready for Phase 3.",
      "actions": [
        {
          "type": "screen",
          "screener": "5",
          "cutter": "2",
          "at": "left_block",
          "cutter_to": "left_wing"
        },
        {
          "type": "cut",
          "player": "3",
          "to": "left_slot",
          "bias": "toward_basket"
        },
        {
          "type": "cut",
          "player": "4",
          "to": "right_short_corner",
          "bias": "toward_basket"
        }
      ]
    },
    {
      "label": "Phase 3",
      "text": "If 2 is not open, 5 pivots and screens for 3, who then cuts off sequential screens from 5 and 4 along the baseline and pops to the right wing. 1 hits 3 on the inside shoulder for the shot.",
      "detail": "Secondary read. 3 sprints the baseline, using 5's screen first, then 4's screen, to emerge at the right wing. 1 passes to 3's inside shoulder so 3 can curl naturally into the shot.",
      "actions": [
        {
          "type": "screen",
          "screener": "5",
          "cutter": "3",
          "at": "baseline_center",
          "cutter_to": "right_wing"
        },
        {
          "type": "pass",
          "from_player": "1",
          "to_player": "3"
        }
      ]
    }
  ]
} as const;

export const slobX: Play = {
  "name": "SLOB X",
  "tag": "SLOB",
  "desc": "A sideline out-of-bounds box-set play that uses two sequential waves of staggered screens to free two different shooters — first 2 on one wing, then 3 on the opposite wing — for open mid-range or three-point shots. 3 inbounds, 1 receives the entry pass at the top, then looks to kick out to whichever shooter comes free.",
  "players": {
    "1": [
      8,
      19
    ],
    "2": [
      -8,
      19
    ],
    "3": [
      -26,
      25
    ],
    "4": [
      8,
      5
    ],
    "5": [
      -8,
      5
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Guard 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "3",
  "phases": [
    {
      "label": "Phase 1",
      "text": "2 sets a diagonal down-screen for 1, who pops to the top of the key. 3 inbounds to 1 and steps onto the court.",
      "detail": "Entry action. 2 uses the screen as a decoy/setter — their cut to the screen frees 1 to pop to the top. 3 delivers the inbound pass to 1 at the top of the key and immediately enters the court near the left wing area.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 19 C -4.61 15.55, -1.95 14.22, 0 15",
          "move": {
            "id": "2",
            "to": [
              0,
              15
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 19 C 2.99 21.89, 0.33 26.23, 0 32",
          "move": {
            "id": "1",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -26 25 L 0 32",
          "dashed": true,
          "ball": {
            "from": "3",
            "to": "1"
          }
        }
      ]
    },
    {
      "label": "Phase 2",
      "text": "2 cuts off a staggered screen set first by 5 then by 3, curling out to the left wing for the primary shot look. 4 walks down toward the right block to set up the next action.",
      "detail": "Primary read: 1 looks to hit 2 on the left wing off the staggered screens from 5 and 3. 4 repositions to the right short corner to be ready for Phase 3.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 5 C -8 5, -8 5, -8 5",
          "move": {
            "id": "5",
            "to": [
              -8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 15 C -6.26 14.63, -11.26 16.97, -15 22",
          "move": {
            "id": "2",
            "to": [
              -15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -26 25 C -19.64 23.79, -15.3 24.79, -13 28",
          "move": {
            "id": "3",
            "to": [
              -13,
              28
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 5 C 8.66 4.79, 11.32 4.46, 16 4",
          "move": {
            "id": "4",
            "to": [
              16,
              4
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 3",
      "text": "If 2 is not open, 5 pivots and screens for 3, who then cuts off sequential screens from 5 and 4 along the baseline and pops to the right wing. 1 hits 3 on the inside shoulder for the shot.",
      "detail": "Secondary read. 3 sprints the baseline, using 5's screen first, then 4's screen, to emerge at the right wing. 1 passes to 3's inside shoulder so 3 can curl naturally into the shot.",
      "actions": [
        {
          "marker": "screen",
          "path": "M -8 5 C -3.38 4.76, -0.72 3.43, 0 1",
          "move": {
            "id": "5",
            "to": [
              0,
              1
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -13 28 C -2.83 29.91, 6.5 27.91, 15 22",
          "move": {
            "id": "3",
            "to": [
              15,
              22
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 32 L 15 22",
          "dashed": true,
          "ball": {
            "from": "1",
            "to": "3"
          }
        }
      ]
    }
  ]
};
