// GENERATED by scripts/synthesize-plays.ts — do not edit by hand.
// Source: wiki slug "blob-4-low-flex-updated"
// Semantic source retained for audit — modify the semantic form, then re-run the synthesizer.
import type { Play } from "@/lib/types";

export const blob4LowFlexUpdatedSemantic = {
  "name": "BLOB 4-Low Flex",
  "tag": "BLOB",
  "desc": "From a 4-low formation, the ball is inbounded to a cutter at the top of the key. The play flows into a flex screen for a post layup (primary), then a screen-the-screener pin-down action that frees the inbounder (best shooter) at the top of the key for a catch-and-shoot (secondary).",
  "players": {
    "1": "left_block",
    "2": "baseline_center",
    "3": "right_block",
    "4": "right_elbow",
    "5": "right_wing"
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Shooter 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "2",
  "phases": [
    {
      "label": "Phase 1 — Inbound & Ball Movement",
      "text": "4 cuts from the elbow to the top of the key and receives the inbounds lob pass from 2. 3 waits a beat, then cuts to the top of the key and receives the pass from 4. The delay on 3's cut is critical — cutting too early tips off the defense.",
      "actions": [
        {
          "type": "cut",
          "player": "4",
          "to": "top_of_key"
        },
        {
          "type": "pass",
          "from_player": "2",
          "to_player": "4"
        },
        {
          "type": "cut",
          "player": "3",
          "to": "top_of_key"
        }
      ]
    },
    {
      "label": "Phase 1b — Pass to 3",
      "text": "4 passes to 3 at the top of the key. 3 is now the decision-maker for the primary and secondary options.",
      "actions": [
        {
          "type": "pass",
          "from_player": "4",
          "to_player": "3"
        }
      ]
    },
    {
      "label": "Phase 2 — Flex Screen for Post Layup (Primary)",
      "text": "2, now stepped inbounds, sets a flex screen for 5. 5 flex-cuts hard toward the ball-side low block, looking for the pass from 3 for an open layup. This is the primary scoring option.",
      "actions": [
        {
          "type": "screen",
          "screener": "2",
          "cutter": "5",
          "at": "left_block",
          "cutter_to": "right_block",
          "bias": "toward_basket"
        },
        {
          "type": "pass",
          "from_player": "3",
          "to_player": "5"
        }
      ]
    },
    {
      "label": "Phase 3 — Screen-the-Screener / Pin Down (Secondary)",
      "text": "After 2 sets the flex screen, 4 immediately sets a pin-down (down screen) for 2. 2 cuts to the top of the key and looks for the catch-and-shoot pass from 3. This screen-the-screener action is the secondary scoring option.",
      "actions": [
        {
          "type": "screen",
          "screener": "4",
          "cutter": "2",
          "at": "left_elbow",
          "cutter_to": "top_of_key",
          "bias": "away_from_basket"
        },
        {
          "type": "pass",
          "from_player": "3",
          "to_player": "2"
        }
      ]
    }
  ]
} as const;

export const blob4LowFlexUpdated: Play = {
  "name": "BLOB 4-Low Flex",
  "tag": "BLOB",
  "desc": "From a 4-low formation, the ball is inbounded to a cutter at the top of the key. The play flows into a flex screen for a post layup (primary), then a screen-the-screener pin-down action that frees the inbounder (best shooter) at the top of the key for a catch-and-shoot (secondary).",
  "players": {
    "1": [
      -8,
      5
    ],
    "2": [
      0,
      1
    ],
    "3": [
      8,
      5
    ],
    "4": [
      8,
      19
    ],
    "5": [
      15,
      22
    ]
  },
  "roster": {
    "1": {
      "name": "Guard 1",
      "pos": "PG"
    },
    "2": {
      "name": "Shooter 2",
      "pos": "SG"
    },
    "3": {
      "name": "Wing 3",
      "pos": "SF"
    },
    "4": {
      "name": "Forward 4",
      "pos": "PF"
    },
    "5": {
      "name": "Post 5",
      "pos": "C"
    }
  },
  "ballStart": "2",
  "phases": [
    {
      "label": "Phase 1 — Inbound & Ball Movement",
      "text": "4 cuts from the elbow to the top of the key and receives the inbounds lob pass from 2. 3 waits a beat, then cuts to the top of the key and receives the pass from 4. The delay on 3's cut is critical — cutting too early tips off the defense.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 8 19 C 2.99 21.89, 0.33 26.23, 0 32",
          "move": {
            "id": "4",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 1 L 0 32",
          "dashed": true,
          "ball": {
            "from": "2",
            "to": "4"
          }
        },
        {
          "marker": "arrow",
          "path": "M 8 5 C 1.5 12.86, -1.17 21.86, 0 32",
          "move": {
            "id": "3",
            "to": [
              0,
              32
            ]
          }
        }
      ]
    },
    {
      "label": "Phase 1b — Pass to 3",
      "text": "4 passes to 3 at the top of the key. 3 is now the decision-maker for the primary and secondary options.",
      "actions": [
        {
          "marker": "arrow",
          "path": "M 0 32 L 0 32",
          "dashed": true,
          "ball": {
            "from": "4",
            "to": "3"
          }
        }
      ]
    },
    {
      "label": "Phase 2 — Flex Screen for Post Layup (Primary)",
      "text": "2, now stepped inbounds, sets a flex screen for 5. 5 flex-cuts hard toward the ball-side low block, looking for the pass from 3 for an open layup. This is the primary scoring option.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 0 1 C -0.72 3.43, -3.38 4.76, -8 5",
          "move": {
            "id": "2",
            "to": [
              -8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 15 22 C 10.23 14.58, 7.9 8.92, 8 5",
          "move": {
            "id": "5",
            "to": [
              8,
              5
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 32 L 8 5",
          "dashed": true,
          "ball": {
            "from": "3",
            "to": "5"
          }
        }
      ]
    },
    {
      "label": "Phase 3 — Screen-the-Screener / Pin Down (Secondary)",
      "text": "After 2 sets the flex screen, 4 immediately sets a pin-down (down screen) for 2. 2 cuts to the top of the key and looks for the catch-and-shoot pass from 3. This screen-the-screener action is the secondary scoring option.",
      "actions": [
        {
          "marker": "screen",
          "path": "M 0 32 C -2.09 24.72, -4.75 20.39, -8 19",
          "move": {
            "id": "4",
            "to": [
              -8,
              19
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M -8 5 C -6.2 16.87, -3.53 25.87, 0 32",
          "move": {
            "id": "2",
            "to": [
              0,
              32
            ]
          }
        },
        {
          "marker": "arrow",
          "path": "M 0 32 L 0 32",
          "dashed": true,
          "ball": {
            "from": "3",
            "to": "2"
          }
        }
      ]
    }
  ]
};
